### ISSUE TITLE
bilibili.com: ads

### ISSUE THREAD

**Issue by starxjys** [uBlockOrigin/uAssets#14210]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [ ] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

ads

### Describe the issue

Advertising flashing

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.43.0
Chromium: 103
filterset (summary): 
  network: 97456
  cosmetic: 55413
  scriptlet: 17657
  html: 0
listset (total-discarded, last updated): 
  default: 
    user-filters: 0-0, never
    CHN-0: 28522-91, 2h.19m
    easylist: 69001-74, 2h.18m
    easyprivacy: 27473-147, 2h.17m
    plowe-0: 3645-781, 11d.19h
    ublock-abuse: 76-0, 12d.6h.27m
    ublock-badware: 4170-92, 2h.16m
    ublock-filters: 32418-141, 2h.15m
    ublock-privacy: 225-3, 12d.6h.24m
    ublock-quick-fixes: 354-72, 2h.5m
    ublock-unbreak: 1852-43, 2h.13m
    urlhaus-1: 4401-0, 2h.4m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 189 ms (selfie)
  maxAssetCacheWait: 86 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by MasterKia** [comment]
> Advertising flashing

Screenshot?

**Comment by starxjys** [comment]
> > Advertising flashing
> 
> Screenshot?

https://s1.328888.xyz/2022/08/02/OhYDh.gif

**Comment by MasterKia** [comment]
Weird. I couldn't reproduce on Firefox.

**Comment by starxjys** [comment]
It happens when I use edge and chrome

**Comment by JobcenterTycoon** [comment]
Works fine for me on Chrome too.

> popupPanel: 
>   blocked: 0

Looks wrong too, i get blocked requests. Be sure no other adblocker extensions are running and try to reinstall uBlock Origin if this behavior still persist

**Comment by starxjys** [comment]
But just now I installed Chrome, and uBlockOrigin specifically for testing, there are no other advertising plug-ins

**Comment by JobcenterTycoon** [comment]
@Yuki2718 please take a look

**Comment by starxjys** [comment]
Please make sure the website interface is the same as mine, if it is different, please press this button
https://sm.ms/image/UqfY9Ari7BlNCjv

**Comment by QinyuShuai** [comment]
Me too. It happens when I use edge

**Comment by MasterKia** [comment]
Disable Edge's tracking protection and test again.

**Comment by Yuki2718** [comment]
Please highlight ads in screenshot.

**Comment by starxjys** [comment]
> Please highlight ads in screenshot. I don't see obvious ads in `https://s1.328888.xyz/2022/08/02/OhYDh.gif`

Flashing parts

**Comment by Yuki2718** [comment]
Did you made them flash or is this by itself? In any case they are not ads.

**Comment by starxjys** [comment]
> Have you made them flash or do they flash by themselves? In any case they are not ads but promotion. Add `bilibili.com##.eva-extension-feed-area` to My filters.

The "推广" above the blinking section means that the following videos are promotional content and may not be strictly defined as ads, but uBlockOrigin makes them blink，this is also a bug

**Comment by Yuki2718** [comment]
> uBlockOrigin makes them blink

I can't reproduce.

We don't generally block self-promotion. If intrusive or annoying, they may be added to Annoyances lists, but I don't feel this annoying.

**Comment by starxjys** [comment]
I don't think these should be removed either, but it is true that uBlockOrigin is causing the flickering, and turning on uBlockOrigin on my new chrome installation will cause this problem, turning it off will be fine

**Comment by MasterKia** [comment]
> EasyList blocks some self-promotion, but that's their decision and not us.

They block self-promotion for arbitrary reasons or just the annoying ones?

**Comment by MasterKia** [comment]
@starxjys 

Click on the uBlock Origin icon then click on the eye icon to disable cosmetic filters.
Reload the page and see if it's still flashing.

**Comment by starxjys** [comment]
> @starxjys
> 
> Click on the uBlock Origin icon then click on the eye icon to disable cosmetic filters. Reload the page and see if it's still flashing.

It no longer flashes

**Comment by MasterKia** [comment]
Click again on the eye icon to enable cosmetic filters.

Then add this to "My filters" and see if it flashes:

`@@||bilibili.com^$ghide`

**Comment by starxjys** [comment]
> Click again on the eye icon to enable cosmetic filters.
> 
> Then add this to "My filters" and see if it flashes:
> 
> `@@||bilibili.com^$ghide`

Will still continue to flash

**Comment by MasterKia** [comment]
> > disable cosmetic filters. Reload the page and see if it's still flashing.
> 
> It no longer flashes

I checked the logger on Firefox. There is no cosmetic filter applying to this site.
Then how come the problem is fixed when you disable cosmetic filters?

@Yuki2718 
Do you get any cosmetic filters on this site?

**Comment by starxjys** [comment]
Sorry, all I know is that when I click on the "eye" it stops blinking, including after the page is refreshed. But after I open it and refresh the page it continues to blink

**Comment by JobcenterTycoon** [comment]
After i got the site like mentioned here https://github.com/uBlockOrigin/uAssets/issues/14210#issuecomment-1202337975 `bilibili.com##.banner-card` getting applied

**Comment by MasterKia** [comment]
With the **_cosmetic filters enabled_** (the eye icon should be visible), add this to "My filters" and test again:
`bilibili.com#@#.banner-card`

**Comment by starxjys** [comment]
> With the **_cosmetic filters enabled_** (the eye icon should be visible), add this to "My filters" and test again: `bilibili.com#@#.banner-card`

This did not solve the problem, but when I clicked the button to update the rule the problem seemed to be solved and the flickering problem did not occur again. Anyway, the problem was solved

**Comment by starxjys** [comment]
Well, it hasn't been completely solved. It reared its ugly head once again." bilibili.com#@#.banner-card" doesn't solve the problem

**Comment by Yuki2718** [comment]
> After i got the site like mentioned here

By that operation `bilibili.com##a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"])` and `
bilibili.com##.eva-banner` are applied on my end but no `##.banner-card` hit and no flickring.

**Comment by MasterKia** [comment]
@starxjys 

Try:
```
bilibili.com#@#a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"])
bilibili.com#@#.eva-banner
bilibili.com#@#.banner-card
```

**Comment by starxjys** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/42333314/182424271-3480b29f-8e9d-4a0e-80bd-92797f12f511.png)
I don't know if I'm doing it right, but it doesn't work when set up like this

**Comment by Yuki2718** [comment]
Does that happen to other browser?

**Comment by starxjys** [comment]
> Does that happen to other browser?

chrome and edge

**Comment by MasterKia** [comment]
> Like this?

Yes.



> but it doesn't work when set up like this

Click on uBlock Origin icon. Click on this icon (you have to press "More" a few times if you can't see it").
![Screenshot_20220802_210140](https://user-images.githubusercontent.com/17685483/182426478-d8540933-2072-4851-a112-49a4576dd0ea.png)

Set in on "blocked" mode:
https://user-images.githubusercontent.com/17685483/182426580-c1ed94a9-ced6-48d7-8e7a-47ba80d4db9c.png

Open the site and send screenshot from the whole list.

**Comment by starxjys** [comment]
![image](https://user-images.githubusercontent.com/42333314/182427299-d457d39a-aa2a-4f21-a126-3827cfbc801f.png)

**Comment by starxjys** [comment]
![Snipaste_2022-08-03_00-36-18](https://user-images.githubusercontent.com/42333314/182427371-3808da82-88a4-423b-af68-df7a4f05050d.png)

**Comment by MasterKia** [comment]
![Screenshot_20220802_210955](https://user-images.githubusercontent.com/17685483/182427974-59313984-e437-4f4a-a7fd-7c493d584de2.png)

Where is this coming from?

Try:
`bilibili.com#@#.bili-video-card:has(.bili-video-card__info--ad-img)`

**Comment by starxjys** [comment]
![image](https://user-images.githubusercontent.com/42333314/182429172-fd14b998-bee0-4565-ac6c-29523ae932be.png)
![image](https://user-images.githubusercontent.com/42333314/182429180-41480797-8424-48fe-87ef-2556ee023b69.png)
It solves the flickering problem, but the ads are not removed instead

**Comment by MasterKia** [comment]
Remove the filter I gave you, then reload the page and go back to the Logger.

Then click on that filter and send screenshot.
Like this:
https://user-images.githubusercontent.com/17685483/182430144-2c0f001f-23c0-4a29-80cd-25ce6e7de712.png

**Comment by JobcenterTycoon** [comment]
The filter coming from Adguard chinese. Maybe this help against the ad and the flickering:  `bilibili.com##.bili-video-card:has(.bili-video-card__info--ad-img):remove()`

**Comment by starxjys** [comment]
> Remove the filter I gave you, then reload the page and go back to the Logger.
> 
> Then click on that filter and send screenshot. Like this: https://user-images.githubusercontent.com/17685483/182430144-2c0f001f-23c0-4a29-80cd-25ce6e7de712.png

![image](https://user-images.githubusercontent.com/42333314/182431412-a9bdfe7c-ca1e-4414-a49c-24940c5108bc.png)




> The filter coming from Adguard chinese. Maybe this help against the ad and the flickering:
> 
> `bilibili.com##.bili-video-card:has(.bili-video-card__info--ad-img):remove()`

It solves the flicker but leaves the ads

**Comment by MasterKia** [comment]
Try:
```
bilibili.com#@#.bili-video-card:has(.bili-video-card__info--ad-img)
bilibili.com##.bili-video-card:has(.bili-video-card__info--ad-img):remove()
```

**Comment by MasterKia** [comment]
@Yuki2718 

Could you fix it in AdGuard Chinese?

**Comment by Yuki2718** [comment]
@starxjys Keep only these two lines in My filters:
```
bilibili.com##.bili-video-card:has(.bili-video-card__info--ad-img):remove()
bilibili.com#@#.bili-video-card:has(.bili-video-card__info--ad-img)
```
And see if
1. Flickering does not occur
2. Ads are not shown

**Comment by starxjys** [comment]
> Try:
> 
> ```
> bilibili.com#@#.bili-video-card:has(.bili-video-card__info--ad-img)
> bilibili.com##.bili-video-card:has(.bili-video-card__info--ad-img):remove()
> ```

It works well
![image](https://user-images.githubusercontent.com/42333314/182432802-5dc00e42-48aa-41d2-9baf-aeeb690d7e8c.png)

**Comment by Yuki2718** [comment]
Okay, will fix.

**Comment by MasterKia** [comment]
Maybe remove the "unable to reproduce" as well.

**Comment by Yuki2718** [comment]
Wait... this seems to be came from EL China @cjx82630

**Comment by MasterKia** [comment]
https://user-images.githubusercontent.com/42333314/182431412-a9bdfe7c-ca1e-4414-a49c-24940c5108bc.png

**Comment by Yuki2718** [comment]
AG Chinese is ELC + its own part.

**Comment by cjx82630** [comment]
[Fixed.](https://github.com/easylist/easylistchina/commit/d0b85404eec201173c7d4864d240c7454c5ba10b)
