### ISSUE TITLE
bilibili.com: detection

### ISSUE THREAD

**Issue by tasty0tomato** [uBlockOrigin/uAssets#15433]
### Prerequisites

- [X] I read and understood the [policy as to what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets)
- [X] I verified that the issue has not already been reported (use [this button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out)
- [X] I forced an update of my filter lists (**how to do this:** [click _"Purge all caches"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#purge-all-caches), then [click _"Update now"_](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now))
- [X] I did not remove any of the [default filter lists](https://user-images.githubusercontent.com/585534/91296476-ab9d8c00-e76a-11ea-9fb9-87d6861bdf73.png), or I verified that the issue is not caused by removing any of the default lists
- [X] I did not enable external filter lists, or I verified that the issue still occurs without enabling external filter lists
- [X] I do not have custom filters/rules, or I verified that the issue still occurs without custom filters/rules
- [X] I am not using [another content blocker along uBO](https://twitter.com/gorhill/status/1033706103782170625) (also mind browser built-in blockers)
- [X] I did not answer truthfully to **all** the above checkpoints

### URL address of the web page

`https://www.bilibili.com/`

### Category

detection

### Describe the issue

bilibili finds Ublock

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![www bilibili com_](https://user-images.githubusercontent.com/48764449/198258577-108a5939-0a9c-45e2-afb4-4b38b6e99c57.png)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 107
filterset (summary): 
  network: 62070
  cosmetic: 78930
  scriptlet: 18151
  html: 0
listset (total-discarded, last updated): 
  removed: 
    easyprivacy: null
    plowe-0: null
    ublock-abuse: null
    ublock-badware: null
    ublock-privacy: null
    ublock-quick-fixes: null
    urlhaus-1: null
  added: 
    https://www.i-dont-care-about-cookies.eu/abp/: 25450-4, 1d.23h.46m
    CHN-0: 28953-91, 3d.5h.5m
    JPN-1: 8128-16, 1d.23h.47m
  default: 
    user-filters: 0-0, never
    easylist: 62008-136, 4d.8h.2m
    ublock-filters: 33193-136, 3d.5h.7m
    ublock-unbreak: 1877-22, 3d.5h.6m
filterset (user): [empty]
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 247 ms (selfie)
  maxAssetCacheWait: 173 ms
popupPanel: 
  blocked: 0
```
</details>

**Comment by stephenhawk8054** [comment]
Looks like because of this filter in `EasyList China`

```adb
bilibili.com##a[href*="cm.bilibili.com"][data-target-url]:not([data-target-url*=".bili"])
```

@cjx82630 Sorry can you check this issue?

**Comment by cjx82630** [comment]
Please add this list which removes anti-adblock/annoyances https://main.filter-delivery-staging.eyeo.com/v3/full/cjx-annoyance.txt

**Comment by tasty0tomato** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/133511

**Comment by stephenhawk8054** [comment]
> [AdguardTeam/AdguardFilters#133511](https://github.com/AdguardTeam/AdguardFilters/issues/133511) Maybe help?

Have you added the above filter list?

> Please add this list which removes anti-adblock/annoyances https://main.filter-delivery-staging.eyeo.com/v3/full/cjx-annoyance.txt

**Comment by tasty0tomato** [comment]
> Have you added the above filter list?

Yes, it works.

**Comment by tasty0tomato** [comment]
@cjx82630 Is there a way to not let _bilibili_ find _ublock origin_ and why to put _bilibili_ in the filter?

**Comment by tasty0tomato** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/133511#issuecomment-1296760996

**Comment by stephenhawk8054** [comment]
> Please add this list which removes anti-adblock/annoyances https://main.filter-delivery-staging.eyeo.com/v3/full/cjx-annoyance.txt

You can add this list or enable `Adguard Annoyances` list?

**Comment by tasty0tomato** [comment]
@stephenhawk8054 Yes, both work.

**Comment by stephenhawk8054** [comment]
Yes, then the issue is solved.

**Comment by tasty0tomato** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/133511#issuecomment-2321184348
Again, the filter is found again. Should I open a new issue to report?

**Comment by stephenhawk8054** [comment]
Just continue here

**Comment by tasty0tomato** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/187910 
It seems that ad been found in bilibili is figured out in only AdGuard, but it still occurs in only Ublock Origin. So maybe I should ask for help from here.

**Comment by stephenhawk8054** [comment]
Does the list here work?

**Comment by tasty0tomato** [comment]
This link cannot be used anymore.

**Comment by stephenhawk8054** [comment]
Then you can report to this: https://github.com/cjx82630/cjxlist/issues

**Comment by tasty0tomato** [comment]
@stephenhawk8054  I have not done what you suggested me to do, but communicated with https://github.com/AdguardTeam/AdguardFilters/issues/187910, and I thought at least all the problems about being detection is done in Adguard, but that still being found in uBlock is not figured out.
[my-ublock-backup_2024-09-19_07.24.08.txt](https://github.com/user-attachments/files/17051025/my-ublock-backup_2024-09-19_07.24.08.txt)

I am not sure if it is the issue about https://github.com/cjx82630/cjxlist, because I have never used this one.
