### ISSUE TITLE
Ads in default filter are allowed for gelbooru.com

### ISSUE THREAD

**Issue by konecat** [uBlockOrigin/uAssets#2187]
I've noticed this in particular with **gelbooru.com**, those two filters in particular:

@@||gelbooru.com^$generichide
@@||gelbooru.com^$first-party,script

Those exceptions make the ad-blocking that site close to impossible. With those taken, it's easy and just requires blocking certain .js scripts. Why not add this if we want to ad-block?
Why does this exist? Is this an ad-blocker, or does someone infiltrate lists to add exceptions to their own sites? Why is this allowed? This is bullshit. At least I can override rules with ,important attribute, but if they do it first on those lists?

I demand those filters are taken down immediately and further modifications be closely observed for manipulation.

**Comment by konecat** [comment]
https://github.com/uBlockOrigin/uAssets/pull/2189

**Comment by mapx-** [comment]
Do you see ads on some gelbooru page ? Upload a screenshot, post the page address.

**Comment by konecat** [comment]
Before:
![2018-05-05-170353_1677x1058_scrot](https://user-images.githubusercontent.com/9724786/39664660-aeaeab36-5086-11e8-811b-8ea4cb0b7a48.png)
After applying:
`||gelbooru.com/script/tryt.js?6$script,first-party,important` filter
![2018-05-05-170148_1685x1059_scrot](https://user-images.githubusercontent.com/9724786/39664666-c08f03fa-5086-11e8-8b4e-c721637902ab.png)

My merge request should fix it.

**Comment by konecat** [comment]
Precise address is https://gelbooru.com/index.php?page=post&s=list&tags=rating%3asafe but the same happens on every other tag. Beware changing tags might show NSFW content.

**Comment by konecat** [comment]
You're right. It was my set-up broken, although the div elements are still there. 
Still, I don't understand the purpose of 
`@@||gelbooru.com^$first-party,script`

It only makes it harder to block the said randomzied div elements with ads created by tryt.js on the page. Even if the ads themselves disappear, the space the occupied don't and make site much less usable.

**Comment by mapx-** [comment]
As I said, I still cannot get all that space, all fine here.
That filter was added to counter scripts like:
`https://gelbooru.com/ads.js`

used to check if an adblocker is enabled.

**Comment by uBlock-user** [comment]
I can reproduce ads.

https://i.gyazo.com/03d2dd28872bbac99d92b7221812bfae.png
https://i.gyazo.com/d6bb09d1903077ea7a8e3d2832cb5a44.png

**Comment by mapx-** [comment]
@uBlock-user  are you using the default setup ?

**Comment by uBlock-user** [comment]
No. Adding `||gelbooru.com/bluet.wry^` fixes it on my end.

**Comment by okiehsch** [comment]
I can't reproduce any ads.

**Comment by uBlock-user** [comment]
Probably because of `||gelbooru.com^$first-party,image` I don't see any ads unless I `badfilter` it.

**Comment by lain566** [comment]
Incorrectly removed element `gelbooru.com##center > a[href]`

`https://gelbooru.com/index.php?page=forum&s=view&id=3955`
![can_i_modify_tag_types_-_forum__gelbooru_-_googl_2018-05-05_20-01-46](https://user-images.githubusercontent.com/27441315/39717799-9e3829c6-5234-11e8-8c3a-91d097c9e8da.png)
