### ISSUE TITLE
kongregate.com: detection

### ISSUE THREAD

**Issue by Vjedi729** [uBlockOrigin/uAssets#23032]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/uBlockOrigin/uAssets/assets/66517106/6e8d024a-5869-47cf-b142-b2357eb6c7d0), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.kongregate.com/accounts/Vsmart/games?filter=favorites`

### Category

detection

### Description

Anywhere on the site, there will be a banner taking the bottom 10% of the windows with the text: 
"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."
Behind it, there is a second banner with similar text:
"You are seeing this message because ad or script blocking software is interfering with this page.
Disable any ad or script blocking software, then reload this page."

Both banners are a light yellow color and contain a "warning icon".

### Other extensions used

Bitwarden

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/uBlockOrigin/uAssets/assets/6351252/25028ced-fcb7-42a5-8998-3bb65fb56da1)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.56.0
Firefox: 123
filterset (summary):
 network: 126809
 cosmetic: 45767
 scriptlet: 19008
 html: 1725
listset (total-discarded, last-updated):
 default:
  user-filters: 7-0, never
  ublock-filters: 37602-141, now
  ublock-badware: 8066-15, now
  ublock-privacy: 782-0, now
  ublock-unbreak: 2305-0, now
  ublock-quick-fixes: 248-0, now
  easylist: 83101-642, now
  easyprivacy: 50405-861, now
  urlhaus-1: 8840-0, now
  plowe-0: 3763-0, now
filterset (user): [array of 7 redacted]
trustedset:
 added: [array of 5 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 3899 ms (selfie)
 maxAssetCacheWait: 757 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 17
 network:
  doubleclick.net: 1
  google.com: 12
  googletagmanager.com: 2
  newrelic.com: 2
```
</details>

**Comment by ItsProfessional** [comment]
It's the google funding choices message, which I'm pretty sure is addressed globally.

@Vjedi729 Do you use network-wide/system-wide blocking (such as pihole, etc.) or a VPN?

**Comment by Yuki2718** [comment]
@Vjedi729 It's likely somthing is interferring on your system. What are `filterset (user): [array of 7 redacted]`? Try to install uBO on a new Firefox profile and check again.

**Comment by gwarser** [comment]
> It's the google funding choices message, which I'm pretty sure is addressed globally.

Can happen when APB is installed alongside uBO if I recall correctly.

**Comment by Yuki2718** [comment]
> * [x]  I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
> * [x]  I am not using uBlock Origin along with other content blockers.
> * [x]  I have verified that other extensions are not causing the issue.

**Comment by Vjedi729** [comment]
When testing on a new Firefox profile, the problem disappears. I believe this problem is specific to my setup. I still don't know why that is the case.

> It's the google funding choices message, which I'm pretty sure is addressed globally.
> 
> @Vjedi729 Do you use network-wide/system-wide blocking (such as pihole, etc.) or a VPN?

I don't have network-wide blocking or a VPN active. 

> @Vjedi729 It's likely somthing is interferring on your system. What are `filterset (user): [array of 7 redacted]`? Try to install uBO on a new Firefox profile and check again.

These are my custom filters, all added using the element picker: 

```! 2023-01-20 https://www.kbb.com
www.kbb.com##.ads__container-kbbLockedAd

! 2024-02-19 https://www.kongregate.com
www.kongregate.com##.lm9irx5p8p8j
www.kongregate.com##.zv6hykraq5l
www.kongregate.com##.riqnii5aogjl
www.kongregate.com##.ayqmbtjkum7u
www.kongregate.com##.\32 40e8i5oeofs
www.kongregate.com##.\37 qeo8p4zm6eq```

Clearing the list does not change or remove the message.

> > It's the google funding choices message, which I'm pretty sure is addressed globally.
> 
> Can happen when APB is installed alongside uBO if I recall correctly.
> 
> Yes, correct - https://twitter.com/gorhill/status/1751231935639060792

I don't know what APB is. I had Ghostery installed, but disabled it to test if that would fix the problem.

**Comment by stephenhawk8054** [comment]
Can you go to `about:addons` page (type in URL bar) and screenshot it here?

**Comment by chsnell** [comment]
Ran into this issue today with uBlockOrigin lite in Chrome.  Disabled ALL filters adding them back one at a time until I hit the issue.  The issue appears when the uBlock filters (https://github.com/uBlockOrigin/uAssets) are enabled, and happen for any game on Kongregate that I've tried.

**Comment by gothic-bum** [comment]
@chsnell 

Test again using a new Chrome profile with only uBO Lite and its default settings.

**Comment by stephenhawk8054** [comment]
Test again in a new browser profile with only uBO and its default settings.

**Comment by chsnell** [comment]
That was tested with a profile with all other extensions disabled and coming from the default settings of uBlock origin lite.

**Comment by stephenhawk8054** [comment]
Can you go to `chrome://extensions` and screenshot to here?

Then can you screenshot the whole site?

**Comment by chsnell** [comment]
<details>

<img width="1455" height="798" alt="Image" src="https://github.com/user-attachments/assets/c37b007e-f4de-4394-bc85-a766c9999ead" />
<img width="1464" height="651" alt="Image" src="https://github.com/user-attachments/assets/94de539f-3551-4b5a-8276-5371b62ab968" />

</details>

**Comment by gothic-bum** [comment]
Paste the following into `uBO Lite dashboard` > [`Develop`](https://github.com/uBlockOrigin/uBOL-home/wiki/Dashboard:-Develop) > `Custom DNR rules` : 
  
    @@||fundingchoicesmessages.google.com^$script,domain=kongregate.com

Then restart your browser, open a new tab, and test again.

**Comment by chsnell** [comment]
Confirmed that works, although not the easiest to find where to put with those limited directions.  Worked even without restarting the browser.
