### ISSUE TITLE
[Anti-adblock] kissasian.ch

### ISSUE THREAD

**Issue by TheHungryGeek** [uBlockOrigin/uAssets#2465]
Replace the bracketed [...] placeholders with your own information.

### URL(s) where the issue occurs

`http://kissasian.ch/Drama/My-Mister/Episode-1?id=36170`

### Describe the issue

Forces an adblock disable before allowing the video to play

### Screenshot(s)

![image](https://user-images.githubusercontent.com/16078559/40920007-e73f5cd8-683d-11e8-9558-a210fc509458.png)

### Versions

- Browser/version: Chrome 66
- uBlock Origin version: 1.16.8

### Settings

- All default

**Comment by mapx-** [comment]
Unable to reproduce.

**Comment by TheHungryGeek** [comment]
This was apparently flagged 2 days ago.

https://github.com/uBlockOrigin/uAssets/issues/2450

How do I manually add the lines to fix this? Thanks for the help!

**Comment by nimasaj** [comment]
@TheHungryGeek , you just need to update uBlock filters. Go to filter lists and force them to update.

**Comment by mapx-** [comment]
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters#update-now

**Comment by TheHungryGeek** [comment]
Thanks, tried all that and cleared the cache, restarted my browser - issue remains

**Comment by nimasaj** [comment]
@TheHungryGeek Can you post a screenshot of your logger?

**Comment by TheHungryGeek** [comment]
![image](https://user-images.githubusercontent.com/16078559/40921233-74a83556-6841-11e8-9e05-06eca8f1c98f.png)

**Comment by TheHungryGeek** [comment]
![image](https://user-images.githubusercontent.com/16078559/40921304-a7cc78de-6841-11e8-8475-140036069651.png)

Filters seem to be registering, but the video is still blocked

**Comment by nimasaj** [comment]
what filter lists are you subscribed to?

**Comment by TheHungryGeek** [comment]
![image](https://user-images.githubusercontent.com/16078559/40921462-133d5bec-6842-11e8-97e2-6dd400f82d8f.png)

**Comment by mapx-** [comment]
- remove aaklist - outdated
- then try only the default setup

**Comment by nimasaj** [comment]
Can you uncheck following filter lists and report back the result?
- my filters
- Adblock warning removal list
- all Custom filter lists

**Comment by TheHungryGeek** [comment]
Unchecked all as instructed, restarted browser, video still blocked

**Comment by TheHungryGeek** [comment]
I'm using Nano Defender for the enhanced anti-adblock features that is supposed to work on top of uBO (it actually requires uBO to work).

https://jspenguin2017.github.io/uBlockProtector/

Oh well I'll give it a few days and hope it resolves itself. Thank you for all the help!

**Comment by mapx-** [comment]
@jspenguin2017

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Use the Quick Issue Reporter next time. It saves everyone's time. 
![image](https://user-images.githubusercontent.com/7283682/40947753-a99dbb70-6821-11e8-85f2-6f85c919eecf.png)

**Comment by TheHungryGeek** [comment]
Thanks! I was just following the instructions on your Github to report such issues to uAssets XD

**Comment by jspenguin2017** [comment]
> just following the instructions on your Github

I wrote on my GitHub Pages that if the maintainer of uAssets told you the issue could not be reproduced, then ping me immediately. 

Also, your setup is far from `All default`. 

---

You need to update Nano Defender from the extension manager.

**Comment by TheHungryGeek** [comment]
> You need to update Nano Defender from the extension manager.
Nano Defender is showing 14.45, which is the version that is on the Chrome web store. Video is still getting blocked.

I disable all the filter lists that may be conflicting each time to test as well.

**Comment by TheHungryGeek** [comment]
I reset uBO to factory default settings and it loaded fine.

Reinstalled Nano Defender and now its all good. Thanks for your help.
