### ISSUE TITLE
pinterest.com: ads / detection

### ISSUE THREAD

**Issue by d9no** [uBlockOrigin/uAssets#25614]
### Prerequisites

- [X] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/20586), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/17361) report. _These sites MUST be reported by clicking their **respective links**_.
- [X] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [X] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.)
- [X] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [X] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [X] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [X] I am not using uBlock Origin along with other content blockers.
- [X] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [X] I have verified that other extensions are not causing the issue.
- [X] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site issue.
- [ ] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.pinterest.com/`

### Category

detection

### Description

Upon entering the main page of pinterest.com, there appears to be a half transparent gray background with the box in the middle stating;

`Ad Blocker detected
Please disable your ad blocker to access more features and get the full experience of Pinterest.
After you disable the ad blocker, please refresh the page.`

Tried zapping the box and background and was unable to get the page to load further.

Reproduction Steps:
1.  **Log in to a Pinterest account**
2. Navigate to either pinterest.com or pinterest.com/ideas

Unsure why this doesn't happen when you're not logged in.

### Other extensions used

none

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![image](https://github.com/user-attachments/assets/56ed14db-7274-443e-bd33-6fb42d7a3fb0)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.60.0
Chromium: 129
filterset (summary):
 network: 150890
 cosmetic: 48498
 scriptlet: 22809
 html: 0
listset (total-discarded, last-updated):
 removed:
  user-filters: null
 default:
  easylist: 85899-580, 11m Δ
  easyprivacy: 53143-640, 11m Δ
  plowe-0: 3541-0, 2m
  ublock-badware: 11643-6, 11m Δ
  ublock-filters: 40408-258, 11m Δ
  ublock-privacy: 1302-22, 11m Δ
  ublock-quick-fixes: 180-0, 11m Δ
  ublock-unbreak: 2480-0, 11m Δ
  urlhaus-1: 25255-0, 22m
filterset (user): [array of 29 redacted]
trustedset:
 added: [array of 17 redacted]
switchRuleset:
 added: [array of 1 redacted]
userSettings:
 advancedUserEnabled: true
 prefetchingDisabled: false
hiddenSettings: [none]
supportStats:
 allReadyAfter: 944 ms
 maxAssetCacheWait: 157 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 5
 network:
  pinterest.com: 5
 extended:
  ##[data-grid-item]:has([data-test-pin-id] [data-test-id^="one-ta…
  ##+js(json-prune, resource_response.data.[-].pin_promotion_id)
```
</details>

**Comment by d9no** [comment]
Forgot to add the tag to be logged in on this post. Sorry!

**Comment by stephenhawk8054** [comment]
Caused by

```adb
pinterest.com##div[data-test-id="pin"]:has(div[title^="Promoted"])
```

in EL.

cc @Yuki2718

**Comment by stephenhawk8054** [comment]
Fixed in quick fix list. Wait about 10 minutes then click on [this link](https://ublockorigin.github.io/uAssets/update-lists.html?listkeys=ublock-quick-fixes&manual=241013) to force update the quick fix list.

**Comment by stephenhawk8054** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25890

**Comment by stephenhawk8054** [comment]
@Serph Test again in a new Firefox profile with only uBO and its default settings.

**Comment by mapx-** [comment]
@anulal03 which exactly is the ad in your screenshot ?

**Comment by VaporwaveTears** [comment]
Hello! I tried the provided solution. However, I'm not on Firefox & it did not fix the issue. 

<details>

![image](https://github.com/user-attachments/assets/ac3b5080-a19f-4b78-bfbc-a430616afc9c)

</details>

As you can see, now it's worse because there's ads on the home screen. 

<details>

![image](https://github.com/user-attachments/assets/5f352348-4301-4aa2-b540-1958ab6fd386)

</details>

Above is evidence that I'm on a new profile for Safari.

**Comment by stephenhawk8054** [comment]
@D4niloMR Sorry, can you reproduce in any mobile devices?
