### ISSUE TITLE
paypal.com: detection

### ISSUE THREAD

**Issue by C-O-dE** [uBlockOrigin/uAssets#29029]
### Prerequisites

- [x] This is **NOT** a [_YouTube_](https://www.github.com/uBlockOrigin/uAssets/issues/27415), [_Facebook_](https://www.github.com/uBlockOrigin/uAssets/issues/3367), [_Twitch_](https://www.github.com/uBlockOrigin/uAssets/issues/5184) or [_a shortener/hosting site_](https://github.com/uBlockOrigin/uAssets/discussions/27472) report. _These sites MUST be reported by clicking their **respective links**_.
- [x] I read and understand the [policy about what is a valid filter issue](https://github.com/uBlockOrigin/uAssets/blob/master/README.md#uassets).
- [x] I verified that this issue is not a duplicate. (Use this [button](https://user-images.githubusercontent.com/585534/146582579-c32707a0-36a1-4cc5-ad50-83172c9f67a8.png) to find out.). Comment in the old issue threads even when they are closed or even if you have a different problem.
- [x] I did not remove any of the [default filter lists](https://github.com/user-attachments/assets/1879fc88-09bc-4de4-9e2f-3834a6ab396a), or I have verified that the issue was not caused by removing any of the default lists.
- [x] I did not enable additional filter lists, or I have verified that the issue still occurs without enabling additional filter lists.
- [x] I do not have custom filters/rules, or I have verified that the issue still occurs without custom filters/rules.
- [x] I have verified that the web browser's built-in content blocker/tracking protection, [network wide/DNS blocking](https://en.wikipedia.org/wiki/DNS_blocking), or my VPN is not causing the issue.
- [x] I have turned off all other extensions and the issue still persists. (exception "[Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers)").
- [x] If this is about a breakage or detection, I have verified that it is caused by uBlock Origin and isn't a site or browser issue.
- [x] I have verified that the browser I am using is up to date with no pending updates.
- [x] I did not answer truthfully to **ALL** the above checkboxes.

### URL address of the web page

`https://www.paypal.com/signin`

### Category

detection / breakage

### Description

website only shows "Please enable JS and disable any ad blocker", refuses to load while uBO is active

### Browser name

Firefox 128.12.0esr (64-bit)

### Other extensions used

Bitwarden

### Country

USA

### Screenshot(s)

<details>
<summary>Screenshot(s)</summary>

![Image](https://github.com/user-attachments/assets/9b71c719-0a80-4f5a-b49c-77d963881092)

</details>

### Configuration

<details>

```yaml
uBlock Origin: 1.64.0
Firefox: 128
filterset (summary):
 network: 149708
 cosmetic: 41984
 scriptlet: 23643
 html: 2377
listset (total-discarded, last-updated):
 default:
  user-filters: 5-0, never
  ublock-filters: 41083-111, 2m Δ
  ublock-badware: 11407-17, 2m Δ
  ublock-privacy: 3257-2, 2m Δ
  ublock-unbreak: 2709-1, 2m Δ
  ublock-quick-fixes: 478-19, 2m Δ
  easylist: 70135-551, 2m Δ
  easyprivacy: 54199-603, 2m Δ
  urlhaus-1: 32465-0, 2m
  plowe-0: 3418-0, now
filterset (user): [array of 5 redacted]
trustedset:
 added: [array of 1 redacted]
userSettings: [none]
hiddenSettings: [none]
supportStats:
 allReadyAfter: 605 ms (selfie)
 maxAssetCacheWait: 131 ms
 cacheBackend: indexedDB
popupPanel:
 blocked: 1
 network:
  datadome.co: 1
```
</details>

**Comment by C-O-dE** [comment]
fyi: your 'check for duplicate' link just goes to the button PNG, not an actual link

**Comment by stephenhawk8054** [comment]
The PNG link shows you which button to click in uBO to "Find similar reports".

---

Also please test this filter

```adb
@@||paypal.com.first-party-js.datadome.co^$script,domain=paypal.com
```

**Comment by circuitsacul** [comment]
> The PNG link shows you which button to click in uBO to "Find similar reports".
> 
> Also please test this filter
> 
> @@||paypal.com.first-party-js.datadome.co^$script,domain=paypal.com

Adding the filter doesn't change anything for me. I was able to fix it with the following:
```
@@||api-us-east-1.datadome.co^$domain=paypal.com
@@||geo.ddc.paypal.com^$script,domain=paypal.com
@@||ct.ddc.paypal.com.fpc.datadome.co^$script,domain=paypal.com
```

I imagine the first might be region specific.

**Comment by THEtomaso** [comment]
I ran in to the same issue, and reported it yesterday..
here:
https://github.com/AdguardTeam/AdguardFilters/issues/208599/
..and here:
https://github.com/easylist/easylist/issues/22014/

The issue has been fixed in '**AdGuard Tracking Protection filter**' now, but not in '**EasyPrivacy**'.

It has also been discussed here:
`https://old.reddit.com/r/uBlockOrigin/comments/1lmswx4/cant_access_paypal_account/`

**Comment by stephenhawk8054** [comment]
@THEtomaso Does `@@||datadome.co^$script,domain=paypal.com` alone work on your side? Or do you need `@@||geo.ddc.paypal.com^$script,domain=paypal.com`?

**Comment by THEtomaso** [comment]
I tried to log in to PayPal just now, and "luckily" I ran into the same issue.
This was sufficient for me:
```
@@||paypal.com.first-party-js.datadome.co/tags.js
@@||paypal.com.fpc.datadome.co/i.js
```
..but yesterday, that first one wasn't necessary, and I see that **circuitsacul** also mentioned other things.
So, if you're thinking of adding a fix to '**uBlock filters - Unbreak**', then perhaps this would be a better alternative?:
```
||datadome.co^$third-party,badfilter
||datadome.co^$third-party,domain=~paypal.com
```

**Comment by stephenhawk8054** [comment]
@ryanbr

**Comment by THEtomaso** [comment]
PayPal is definitely in the process of changing things up.
I've spent the last half hour troubleshooting yet another login issue, and finally narrowed it down to this:
* What happens?: Login fails, with no captcha.
* Problem filter: **EasyPrivacy**
* Problem rule: `||c.paypal.com^$image,script`
* Blocked script (on my end): `https://c.paypal.com/da/r/fb_fp.js`
* Working fix: `@@||c.paypal.com/da/r/fb*$script`
Note/update: `@@||c.paypal.com/da/r/fb.js$script` already exists in EasyPrivacy, so this fix is actually just a minor tweak.

**Comment by Yuki2718** [comment]
No problem at all here

**Comment by THEtomaso** [comment]
This is not the easiest thing to troubleshoot.
First of all, the issues appears to be regional and/or periodical.
On top of that, some are CNAME connections, which not everyone is filtering.

In the case of that latest blocking issue (`||c.paypal.com^$image,script`), it seems to occur whenever PayPal decides that it's time to identify yourself through the use of an extra security layer..
Normally, a CAPTCHA appears (which needs to be solved), and then a security key is received on your phone.
If the script at `c.paypal.com` is blocked, no captcha appears, and the login simply fails (with no explanation)!

**Comment by ryanbr** [comment]
That rule is old (2018), I suspect this isn't the issue

**Comment by ryanbr** [comment]
Also note paypal has strong anti-VPN protections and will lock down the account and login

**Comment by THEtomaso** [comment]
> That rule is old (2018)

Well, so is this whitelisting:
https://github.com/easylist/easylist/blame/fbbbfa008e05a77993190c8e288847443215a0f2/easyprivacy/easyprivacy_allowlist.txt#L66
..which apparently was based on this report (Feb.2019):
`https://forums.lanik.us/viewtopic.php?t=45528`
Awfully close to what I narrowed this new issue down to, wouldn't you say?

> I suspect this isn't the issue

Fortunately, my findings weren't based on mere suspicions.
Therefore, I hereby suggest adding this to '**uBlock filters - Unbreak**':
```
@@||c.paypal.com/da/r/fb*$script
||datadome.co^$third-party,badfilter
||datadome.co^$third-party,domain=~paypal.com
```
@circuitsacul:
You also mentioned that you needed this whitelisting:
`@@||geo.ddc.paypal.com^$script,domain=paypal.com`
I weren't able to trigger that connection myself.
Could you confirm that this is actually needed on your end (in addition to the rules that I suggested above), and if so; identify the exact filter that is blocking it?

**Comment by ryanbr** [comment]
Just really bad policy just to exempt the entire tracking company domain of  `datadome.co` without finding which tracking network item is causing it.  

* Fine tune the rule to avoid abuse
* Avoid overreaching tracking 
* The absolute minimum needed for a site to work
* Also be reproducible

The only domain I saw was a CNAME (via Firefox)   https://github.com/easylist/easylist/commit/36aad9309fb64c3b280b0fca45fd90e3a501e002

Or the full domain
```
https://ddbm2.paypal.com.first-party-js.datadome.co
```

**Comment by Dragodraki** [comment]
For me it says "Please enable JS and disable any ad blocker".
https://www.paypal.com/signin

If I disable "Uncloak canonical names" in main settings of uBO or EasyList filter in the filter settings, clean the site cache and reload the site, it works again. As soon I enable both, delete the cache and reload the page, paypal refuses to show to login page again.

"Uncloak canonical names" uses EasyList and tha latter became incompatible with the way PayPal performs the login. It should get fixed by the devs.

**Comment by Dragodraki** [comment]
Unfortunately this is not completed!

![Image](https://github.com/user-attachments/assets/0359332f-ef95-4177-ba78-fc13243bb05b)

**Comment by dimisa-RUAdList** [comment]
As far as I can see, in the case of Firefox and uBlock Origin, the problem is still not solved, due to blocking of canonical names. To check this, you need to open `https://www.paypal.com/signin`, delete cookies and site data, and then refresh the page.

Since this problem is specific to uBlock Origin, I believe it should be solved in the uBlock filters - Unbreak filter, by adding the exception `@@||paypal.com^$cname`, as it has always been done in all such cases.

**Comment by krystian3w** [comment]
In this case, I think the only option left is remote desktop after contacting with mapx- or stephenhawk8054 to avoid use working `@@||paypal.com^$cname`.

For increased privacy, you could use a Windows 10 trial from a separate drive and physically or at UEFI level disconnect the disk with private data.

**Comment by stephenhawk8054** [comment]
All of the CNAMEs are already allowed on my side:

![Image](https://github.com/user-attachments/assets/8237d5cb-8560-483b-b8a0-07233f536876)

Which connections are still blocked?

**Comment by stephenhawk8054** [comment]
Ah ok, it's `https://ct.ddc.paypal.com.fpc.datadome.co/`

**Comment by dimisa-RUAdList** [comment]
@stephenhawk8054 
In fact, there is enough: `@@||datadome.co/|$domain=paypal.com`

**Comment by Dragodraki** [comment]
The exception does not fix it for me, I just tested it. I cant even enter it because uBO wont let me save it,  probably wrong syntax.
@@||paypal.com^$cname

**Comment by krystian3w** [comment]
Theoretically they don't have to until ABP implements cname.

Brave was supposedly implemented a few years ago as the only Chromium-powered browser with great popularity.

**Comment by uBlock-user** [comment]
@Dragodraki https://github.com/easylist/easylist/commit/36aad9309fb64c3b280b0fca45fd90e3a501e002

**Comment by THEtomaso** [comment]
Even after allowing `datadome.co` and any other CNAME connection, this issue remains:
https://github.com/uBlockOrigin/uAssets/issues/29029#issuecomment-3027639152
..which I elaborated on here:
https://github.com/uBlockOrigin/uAssets/issues/29029#issuecomment-3028351877

**Comment by Dragodraki** [comment]
The exception does not fix it for me (Firefox).
- updated filter just a few sec ago
- cleared cache
- restarted FF
- still same issue
The case is not solved, please re-open.

**Comment by THEtomaso** [comment]
@Dragodraki:
Does the fix that I suggested here fix things for you?:
https://github.com/uBlockOrigin/uAssets/issues/29029#issuecomment-3029933894

**Comment by stephenhawk8054** [comment]
> updated filter just a few sec ago

The filters are just added. They are not available for auto-update yet. You need to wait for about 5-6 hours.

Try adding this filter manually on your side:

```adb
@@||datadome.co^$domain=paypal.com
```

**Comment by THEtomaso** [comment]
```
@@||datadome.co^$domain=paypal.com
```
The problem with that whitelisting is that it also allows the beacon, which isn't necessary (and normally blocked by **EasyPrivacy**'s `$ping,third-party`).
Other potentially uncessecary connections might also slip through.

**Comment by stephenhawk8054** [comment]
The filter added in the main lists is `@@||datadome.co/|$domain=paypal.com`. How does the beacon URL look like?

**Comment by Dragodraki** [comment]
@THEtomaso 
Yes, that is is a working fix.
Thank you very much :)

**Comment by THEtomaso** [comment]
> How does the beacon URL look like?

Unfortunately, I weren't able to trigger it now.
Currently, I only see the ones for `||browser-intake-*-datadoghq.com` and `||paypal.com/platform/tealeaftarget`.
..but I'm pretty sure that I saw one for `datadome.co` yesterday.

**Comment by Yuki2718** [comment]
> The exception does not fix it for me, I just tested it. I cant even enter it because uBO wont let me save it, probably wrong syntax. @@||paypal.com^$cname

The syntax is correct, you must have done something wrong.

**Comment by Dragodraki** [comment]
> > The exception does not fix it for me, I just tested it. I cant even enter it because uBO wont let me save it, probably wrong syntax. @@||paypal.com^$cname
> 
> The syntax is correct, you must have done something wrong.

The name "exception" suggested to insert it into the exception list, therefore the syntax seems wrong. How was I supposed to know that by "exception" the official customized filters were meant?

**Comment by Dragodraki** [comment]
The fix seems to work now in the latest (automatic) filters update of EasyList which means the issue can officially being closed now. uBO now does not indirect block PayPal any longer.

**Comment by THEtomaso** [comment]
> The fix seems to work now in the latest (automatic) filters update of EasyList

You mean '**EasyPrivacy**', but it's NOT fixed in that list yet (and might not ever be), since **ryanbr** only has accepted one small part of the necessary whitelitings.
For the time being, the complete fix is located in '**uBlock filters - Quick fixes**'.

**Comment by THEtomaso** [comment]
@stephenhawk8054 & @ryanbr:

> How does the beacon URL look like?

Hare are a couple of screenshots, which shows the beacon at `datadome.co`:

* **Screenshot 1** (Beacon whitelisted by `@@||paypal.com.first-party-js.datadome.co^$domain=paypal.com` in '**EasyPrivacy**'):
https://github.com/user-attachments/assets/0da521eb-290c-4ca8-b39a-a9e5973ea3a6

* **Screenshot 2** (Beacon blocked by `$ping,third-party` in '**EasyPrivacy**'):
https://github.com/user-attachments/assets/5429c624-a1d4-476a-9852-5fd236e4189a

The payments went through in both cases, so the new whitelistings in '**EasyPrivacy**' and '**uBlock filters - Quick fixes**' can be limited to `$script,xmlhttprequest`.
