### ISSUE TITLE
dinx.in / books-world.net / pc3mag.com [Anti-Adblock]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#3877]
### URL(s) where the issue occurs
`http://dinx.in/`
`http://www.books-world.net/`
`http://pc3mag.com/`

### Describe the issue
Anti-Adblock [annoyance], (have to wait a bit, coz it appears after like 5-10 sec)
enabling Adblock Warning Removal List doesn't fix the issue
enabling Nano Defender doesn't fix the issue
enabling regional lists 2 x CHA + JPN doesn't fix the issue
enabling
uBlock filters – Annoyances​​​​​ +
Adguard’s Annoyance List​​​​​ +
Fanboy’s Annoyance List​ +
doesn't fix the issue

### 1 `http://dinx.in/`
![ss1](https://user-images.githubusercontent.com/43844449/47604863-545bf280-d9ff-11e8-8849-f550073e00f0.png)

### 2 `http://www.books-world.net/`
![ss1](https://user-images.githubusercontent.com/43844449/47605041-ad2c8a80-da01-11e8-9b74-a1a042f011f9.png)

### 3 `http://pc3mag.com/`
![ss1](https://user-images.githubusercontent.com/43844449/47605178-65a6fe00-da03-11e8-8b5a-bcaeaa40c221.png)

### Versions

- OS: Windows 7 SP1 64bit
- Browser/version: Firefox 63.0 64bit
- uBlock Origin version: 1.17.2

### Settings

Default.

**Comment by uBlock-user** [comment]
`/wp-content/plugins/simple-adblock-notice/$first-party`

**Comment by krystian3w** [comment]
Trun on [Adblock Warning Removal List](https://subscribe.adblockplus.org/?location=https%3A%2F%2Feasylist-downloads.adblockplus.org%2Fantiadblockfilters.txt&title=Adblock%20Warning%20Removal%20List)?

```
! *** antiadblockfilters:antiadblockfilters/antiadblock_finnish.txt ***
! *** antiadblockfilters:antiadblockfilters/antiadblock_french.txt ***
!
/ad-blocking-advisor/*
/adblock-notice-
/adblock-notify-by-bweb/*
/adblock-warning-teaser/*
/adblock_gate/images/animated.gif?
/adblock_notify.js
/adblocker_message_
/AdblockMessage.
/antiadblockmsg.
/simple-adblock-notice/*
```

**Comment by mapx-** [comment]
well, a message on the left bottom ..

**Comment by kulfoon** [comment]
Despite the new commit, I still have it.

**Comment by okiehsch** [comment]
![image](https://user-images.githubusercontent.com/16838044/47608075-f8a65f00-da28-11e8-961a-b2619e55015b.png)

**Comment by mapx-** [comment]
tested again FF / chrome, no issue here.

Did you test only using uBo ? (no nano or other blocking extensions)

**Comment by kulfoon** [comment]
Yes, no Nano, no other lists, only uBO default, uBO lists updated (contains the new commit), checked on two browsers: Firefox and Opera, and I still do have it.

**Comment by uBlock-user** [comment]
> Despite the new commit, I still have it.

Must be pulling from the cache, do a full reload of the page via ctrl + R

**Comment by kulfoon** [comment]
I did before, cache & cookies was cleared and I use CTRL + F5 always / also paste the link into new tab, tried several times and still I do have it.

**Comment by okiehsch** [comment]
Can you see the `generichide` filter in your logger ?

**Comment by kulfoon** [comment]
Sure, I even have now:
- used "clear all cache" button in uBO
- used "restore uBO default settings" button 
- activated uBO annoyances list  
- updated filter lists

 and still it is here

**Comment by okiehsch** [comment]
You can try
`dinx.in##+js(setTimeout-defuser.js, Adblocker, 10000)`

**Comment by kulfoon** [comment]
Fixed with your filter, I still wonder anyway why other people couldn't reproduce...

**Comment by okiehsch** [comment]
I still can't reproduce and that filter simply disables the check for some elements, that check will fail if you disable cosmetic filtering, so the `generichide` filter will lead to the same result, atleast in theory.

**Comment by kulfoon** [comment]
Well, I can reproduce even if I disable cosmetic filtering.

**Comment by okiehsch** [comment]
I will add the `setTimeout-filter`, there is no need to spend a lot of time trying to find out why `generichide` does not work for you

**Comment by okiehsch** [comment]
> spend a lot of time trying to find out why generichide does not work for you.

I can see from your logger that `generichide` hide did work on your end, i.e. generic cosmetic filtering **is** disabled,, so I should have phrased that differently, what I meant is: why `generichide` does not fix the issue for you.

**Comment by kulfoon** [comment]
@mapx- @ZaphodBeebblebrox @okiehsch 

Today it came back again for me: 
`http://www.books-world.net/`
`http://pc3mag.com/`

**Comment by kulfoon** [comment]
Have found one more: `http://www.centrumher.eu/` (enabling regional CZE and SVN lists doesn't fix the issue).

**Comment by kulfoon** [comment]
### URL(s) where the issue occurs

`http://endorfinese.com.br/`

### Describe the issue

Anti-Adblock

### Screenshot(s)

![capture_039_13-05-2020_14-05-39](https://user-images.githubusercontent.com/43844449/81810342-119b3600-9523-11ea-84d6-5c6308f043b3.gif)

### Versions

- Browser/version: Firefox 76.0.1
- uBlock Origin version: 1.26.2

### Settings

Default

**Comment by mapx-** [comment]
I cannot reproduce the issue

**Comment by gwarser** [comment]
I see these remnants on main page on `http://endorfinese.com.br/`. It can pop after few seconds or after navigation.

BTW, `/wp-content/plugins/simple-adblock-notice/*` is whitelisted in EasyList.

**Comment by kulfoon** [comment]
Weird, I still can reproduce, on both browsers: Firefox and Opera, it seems that's the same reproducibility issue as discussed in the previous comments for the other websites, but this time it's even more weird because none of filters fix anti-adblock (the HTML filter is not even working - seen in the logger):

```
endorfinese.com.br##+js(nostif, Adblocker, 10000)
endorfinese.com.br##+js(acis, jQuery, undefined)
endorfinese.com.br##^script:has-text(Adblocker)
```

I've attached the zipped website, if anyone would be keen to look at it to see what's going on it would be cool: [Endorfine-se.zip](https://github.com/uBlockOrigin/uAssets/files/4623148/Endorfine-se.zip)

██████████████████████████████████████████████████████████████



Btw, fyi, these filters:
`/wp-content/plugins/simple-adblock-notice/*`  (uBlock Annoyances list)
`-adblock-notice/*` (Adblock Warning Removal List)
on websites mentioned in the issuse, break it's style, after `$badfilter` ing the both filters, a proper anti-adblock popup is being showed:

![capture_049_13-05-2020_16-23-10](https://user-images.githubusercontent.com/43844449/81831089-38fefc80-953d-11ea-8273-3cc6a90b7af0.gif)

**Comment by mapx-** [comment]
finally I managed to reproduce it, working fine in FF / opera
