### ISSUE TITLE
gazetkonosz.pl [Ads]

### ISSUE THREAD

**Issue by kulfoon** [uBlockOrigin/uAssets#4122]
### URL(s) where the issue occurs

`https://www.gazetkonosz.pl/`

### Describe the issue

Annoying "Reclama" ads words/remains/placeholders (whatever it's called) all over the website.
One of many issues refused (without any kind of explanation) to be fixed in regional list https://github.com/MajkiIT/polish-ads-filter/issues/9154 . 
You can see more similiar issues unfixed here: https://github.com/NanoAdblocker/NanoCore/issues/229#issuecomment-439149600
As per discussion here: https://github.com/NanoAdblocker/NanoCore/issues/229#issuecomment-439156603 I've been requested to report such kind of issues here (but I'm not sure if uAssets can accept it). Whatever, we'll see.

### Screenshot(s)

https://github.com/MajkiIT/polish-ads-filter/issues/9154

### Versions

- Browser/version: Firefox 63.0.1 64bit / Opera 56 64bit
- uBlock Origin version: 1.17.2

### Settings

uBO default

**Comment by okiehsch** [comment]
Why can't this be fixed in the polish list?

**Comment by kulfoon** [comment]
@MajkiIT

**Comment by okiehsch** [comment]
To be clear, I am not saying this should be added to the polish list, it's their decision, I am only saying that this will not be fixed in `uAssets`.

**Comment by kulfoon** [comment]
Ok, just by the way then, to be clear too, from: https://github.com/uBlockOrigin/uBlock-issues/issues/301#issuecomment-436961009

> gorhill: If anything is missing in the current POL list which is not in that EasyList Polish, I am sure the maintainers of the current POL list will quickly address such issues.

As seen, this statement is not true.

**Comment by kulfoon** [comment]
Sure, now they suddenly have fixed, for show, why they did not fix it earlier (a month ago), when it was reported, together with the other similiar issues...and any ideas what to do now with the remaining issues (https://github.com/NanoAdblocker/NanoCore/issues/229#issuecomment-439149600)? Report here too, so they feel the pressure and fix it? Or report to EasyList Polish?
