### ISSUE TITLE
svonm.com / golem.de - Video playback issues (uBlock filters)

### ISSUE THREAD

**Issue by THEtomaso** [uBlockOrigin/uAssets#5120]
### Affected site:
`http://www.kicker.de/`

### Issue:
Video playback stops after about 13 seconds.

### Example:
`http://www.kicker.de/news/video/2037466/video_vorsichtige-offensive---schalke-und-die-chance-bei-mancity.html`

### Problem filter:
* uBlock filters

### Problem rule:
`||svonm.com/hd-main.js$script,redirect=hd-main.js,domain=4players.de|bento.de|brigitte.de|buffed.de|desired.de|gamesaktuell.de|gamezone.de|gamona.de|giga.de|golem.de|kicker.de|kino.de|myspass.de|pcgames.de|pcgameshardware.de|spiegel.de|spiegel.tv|spielaffe.de|spieletipps.de|t-online.de|tele5.de|thrashermagazine.com|welt.de|videogameszone.de`

### Possible fix:
`@@||svonm.com/hd-main.js$script,domain=kicker.de`

### Note:
The issue only seems to occur when using uBO Legacy.

### Reference (with relevant information):
`https://forum.palemoon.org/viewtopic.php?f=46&t=21644&p=163445#p163443`

--

* OS/version: Windows 8.1 Pro (x64)
* Browser/version: Pale Moon v28.4.0 (x64)
* Adblock Extension/version: uBlock Origin v1.16.4.9 (XUL)

--

**EDIT:**
As it turns out, more sites are affected by similar issues.
See my post here:
https://github.com/uBlockOrigin/uAssets/issues/5120#issuecomment-472497419

**Comment by okiehsch** [comment]
Adding that filter would break the video using Chromium/Chrome.
I can't test with Firefox at the moment..
````
||svonm.com/hd-main.js$script,redirect=hd-main.js,domain=kicker.de`
kicker.de##+js(golem.de.js)
````
is dealing with pre-roll ads at the site.

**Comment by THEtomaso** [comment]
I don't see any video ads at that site, when using the exception rule that I posted.
At least, not in Pale Moon.

**Comment by okiehsch** [comment]
I get the pre-roll ads if I remove both entries using Chromium.
If you also add
`kicker.de#@#+js(golem.de.js)`
do you get them.

**Comment by THEtomaso** [comment]
Nope, still no ads.
They might be blocked by another filter which I'm using though.

**Comment by okiehsch** [comment]
The redirection is needed on my end for the video to play properly using chromium.
Does 
````
!#if env_firefox
@@||svonm.com/hd-main.js$script,domain=kicker.de
!#endif
````
work with Pale Moon?

**Comment by THEtomaso** [comment]
No.

**Comment by okiehsch** [comment]
Well, then there is nothing we can do, I can reproduce pre-roll ads if I remove the entries for all browsers.

**Comment by THEtomaso** [comment]
After further comparing the loggers for uBO Legacy and the WebExtensions version, I now see that the following rule (found in '**uBlock filters**') doesn't load in the legacy version:
`kicker.de,kino.de,meinestadt.de,spieletipps.de##+js(set-constant.js, String.fromCharCode, noopFunc)`

**Comment by okiehsch** [comment]
That filter will not load in Firefox period.

It is part of a block of filters with a
````
!#if env_chromium
!#endif
````
condition, see https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#if-condition

**Comment by THEtomaso** [comment]
OK.
That's the only difference I saw though.

**Comment by okiehsch** [comment]
I have now tested with Firefox stable and the video works fine. 
We can't add your filter for the legacy versions of Firefox and Pale Moon without breaking the site for Chrome users, so I don't know what can be done other than adding your filter to ones own list.

**Comment by mapx-** [comment]
what if you try
```
!#if !env_chromium
!#if !env_firefox
@@||svonm.com/hd-main.js$script,domain=kicker.de
!#endif
!#endif
```

**Comment by THEtomaso** [comment]
I quickly looked through the other sites, included in the uBlock filters rule, and it seems like `Kino.de` is affected in the same way too.

Example:
`https://www.kino.de/film/captain-marvel-2019/`

So, the new exception rule should be updated to include it, like this:
`@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de`

Under Chromium though, the videos won't play at all, as the video windows won't even open!
I haven't figured out which rule is causing it though.

--

For uBO Legacy, the problem also occurs at `giga.de` and `spieletipps.de` (the videos stops after 13-14 seconds).

Examples:
```
https://www.giga.de/downloads/windows-10/news/windows-10-darum-sollten-pc-spieler-das-neue-update-lieber-nicht-installieren-13-03-2019/

https://www.spieletipps.de/artikel/9902/1/
```

But in these cases, simply whitelisting svonm.com/hd-main.js dosn't work! :(

--

I was unable to test @ `tele5.de`, because of region restrictions.

**Comment by mapx-** [comment]
for kino test
`kino.de#@#+js(addEventListener-defuser.js, /^(?:DOMContentLoaded|load)$/, =!0)`

**Comment by mapx-** [comment]
for giga in palemoon needing
`@@||svonm.com/hd-main.js$script,domain=videos.giga.de`

but I get in console

> Cannot play media. No decoders for requested formats: application/javascript

**Comment by THEtomaso** [comment]
> for kino test
`kino.de#@#+js(addEventListener-defuser.js, /^(?:DOMContentLoaded|load)$/, =!0)`

Yes, this seems to fix the issue for Chromium. :thumbsup:
Although, for some strange reason it doesn't show up in uBO's logger.

--

> I get in console
"Cannot play media. No decoders for requested formats: application/javascript"

To reproduce in Pale Moon, you need to disable MSE for WebM video ('Preferences' > 'Content' > 'Video' > 'Enable MSE' for 'WebM video' > *UNCHECK*).

**Comment by mapx-** [comment]
it was already unchecked, how ever giga seems running fine now after retesting it

spieletipps instead I was able to run the video after whitelisting all scripts  / xhr and waiting minutes

**Comment by mapx-** [comment]
It seems very unstable (palemoon). Trying with the same settings 3-4 times I have different results. 
Maybe you should migrate to some other browser. This way you'll have a full uBo (not legacy one)

**Comment by THEtomaso** [comment]
> It seems very unstable (palemoon). Trying with the same settings 3-4 times I have different results.
Maybe you should migrate to some other browser. This way you'll have a full uBo (not legacy one)

Nah, IMO there are too many mystery-connections going on in the background in other browsers, and they leave you with too little control.. especially Chrome-based ones.
Besides, I don't notice any "unstable" behaviour in Pale Moon, related to these video issues.
With uBO disabled, the videos play just fine @ `spieletipps.de`.
I DID however notice some weird behaviour @ `giga.de` (like you described), but after some closer inspection, I've narrowed it down to a site issue..
More specifically, the site seems to enforce badly implemented UA sniffing!
After tweaking Pale Moon's UA a bit, the videos play just fine there as well (with uBO disabled, of course).

**Comment by okiehsch** [comment]
I removed the `kino.de` filter, was redundant anyway I just forgot about it. :(
https://github.com/uBlockOrigin/uAssets/commit/e07b8d8b7a9d0a597fa1e371d2d613b004a2fac7

**Comment by THEtomaso** [comment]
@mapx-:
Instead of tweaking Pale Moon's UA manually (like I did at first), you can simply switch to "Native" mode.
('Preferences' > 'Advanced' > 'General' > 'Compatibility' > 'User Agent Mode' > "Native")
This takes care of the sloppy UA sniffing @ `giga.de`, and makes the filter issue easier to troubleshoot!

**Comment by mapx-** [comment]
ok, using native mode is working all fine on my side (using the whitelisting added above)

**Comment by THEtomaso** [comment]
> using native mode is working all fine on my side (using the whitelisting added above)

Confirmed!
I regret not checking for UA sniffing earlier, as it would have saved us all some unnecessary troubleshooting.
Thanks to both of you, for looking into these issues! :+1:

**Comment by krystian3w** [comment]
Realy fixed bug with conditions? https://github.com/uBlockOrigin/uBlock-issues/issues/270

```
!#if !env_chromium
!#if !env_firefox
!#if !env_edge
!#if !env_safari
!#if !env_mobile


!#endif
!#endif
!#endif
!#endif
!#endif
```

**Comment by okiehsch** [comment]
You are right,

**Comment by mapx-** [comment]
we have to wait a fix from @gorhill

**Comment by okiehsch** [comment]
````
!#if !env_chromium
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#endif
!#if !env_firefox
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#endif
!#if !env_edge
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#endif
!#if !env_safari
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#endif
!#if !env_mobile
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#endif
````
this could work in the meantime.

**Comment by mapx-** [comment]
No, it doesn't. Already the first if will permit FF whitelisting

**Comment by okiehsch** [comment]
Yes you're right that was a silly idea.

**Comment by mapx-** [comment]
Maybe (if parsing more code lines it's difficult) having more conditions on a line would fix the issue

**Comment by okiehsch** [comment]
We could add a Firefox specific `important` block for `svonm.com/hd-main.js` the exception should then still work with Pale Moon.

**Comment by mapx-** [comment]
something like this
```
!#if !(env_chromium & env_firefox & env_edge & env_safari & env_mobile)
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de 
!#endif
```

**Comment by mapx-** [comment]
there are ads only in firefox ?

**Comment by okiehsch** [comment]
At the moment with chromium/chrome 
````
!#if !env_chromium
!#if !env_firefox
!#if !env_edge
!#if !env_safari
!#if !env_mobile
````
the exception does not apply, so no ads.
With Firefox the exception applies and I can see pre-roll ads.
I can't test with Pale Moon.

**Comment by mapx-** [comment]
maybe could help (in the future) having `env_other` too

**Comment by mapx-** [comment]
well, only FF "see" that filter ? and chrome doesn't  ? weird, it's some bug I guess

**Comment by okiehsch** [comment]
It's https://github.com/uBlockOrigin/uBlock-issues/issues/270 as I understand it if you add
````
!#if !env_chromium
!#if !env_firefox
whatever
!#endif
````
"whatever" will only apply for the first, i.e. chromium and not firefox, conditiion,

**Comment by mapx-** [comment]
We could add the whitelisting filter without "if" and the same filter with badfilter for all known envs (with if)

**Comment by okiehsch** [comment]
Just adding
!#if env_firefox
||svonm.com/hd-main.js$script,important,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#endif
and keeping the existing filter seems more straightforward, if it also works for Pale Moon.
That works on my end using Firefox,

**Comment by mapx-** [comment]
for me we should have (I don't understand the bugs the current behaviour on multi included if )
```
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de
!#if !env_chromium
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter
!#endif
!#if !env_firefox
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter
!#endif
!#if !env_edge
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter
!#endif
!#if !env_safari
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter
!#endif
!#if !env_mobile
@@||svonm.com/hd-main.js$script,domain=kicker.de|kino.de|videos.giga.de|video.spieletipps.de,badfilter
!#endif
```

**Comment by gorhill** [comment]
I rather not bloat uBO filters with that kind of fix. A volunteer using a legacy Firefox version of uBO is welcome to create a filter list which contains filters which are specific to the Firefox-legacy version of uBO.

> I don't understand the bugs in the current behaviour on multi included "if"

Known issue: <https://github.com/uBlockOrigin/uBlock-issues/issues/270>.

**Comment by THEtomaso** [comment]
@lassekongo83:
Is this something you'd be willing to take a crack at?

**Comment by gorhill** [comment]
I have create a new list which purpose is to hold filters to fix issues specific to legacy versions of uBO:
https://github.com/uBlockOrigin/uAssets/blob/master/filters/legacy.txt

That list will be automatically enabled in Firefox-legacy version of uBO once it updates `assets.json`.

**Comment by THEtomaso** [comment]
@gorhill:
Actually, this doesn't seem to work.
I just updated to v1.16.4.10, performed a hard purge, and updated my filter list..
However, the legacy filter didn't appear!

**Comment by gorhill** [comment]
It's not a code path I have tried much. After looking into the code, it seems a "Reset to factory" is necessary -- probably "Restore from backup file" would work too). The missing step is that the key `assetSourceRegistry` must be removed from the indexedDB file.

**Comment by THEtomaso** [comment]
I went back to uBO v1.16.4.9.
Now, all of the filters that I mentioned in my previous post updated themselves just fine.
..so there's definitely a regression in v1.16.4.10!

**Comment by gorhill** [comment]
I forgot to bring all changes to `assets.json` in `master` into `firefox-legacy` branch. This is fixed now.

**Comment by THEtomaso** [comment]
> This is fixed now.

Confirmed! :+1: 

I know it's just a very minor thing, but many of the filters in uBO Legacy still requires a filter update to show the new filter names.
And '**AdGuard Social Media filter**' is still missing, until that action has been performed.

**Comment by gorhill** [comment]
All is fine on my side:

![a](https://user-images.githubusercontent.com/585534/54452433-8c07d480-472b-11e9-9c01-9c88b63fbf7b.png)

**Comment by THEtomaso** [comment]
What I ment is that those filters show the wrong filter names, and fails to appear in the filter list, until a filter update has been run for the first time.
Thats why I called it a very minor issue (if it even qualifies as such). :)

**Comment by gorhill** [comment]
> until a filter update has been run for the first time

Yes, this will be fixed whenever there will be a new release for `firefox-legacy`, the `assets.json` in the package is still the one not updated.

**Comment by okiehsch** [comment]
I copied the fix to the legacy list and removed the safari and edge part, I don't think any user of those browsers would ever entertain the idea ofenabling that list.
We should remove the fix from `uBO-filters` in a week or two to make sure that all legacy users have the chance to get the new list.

**Comment by THEtomaso** [comment]
I've announced it in the Pale Moon forum here:
`https://forum.palemoon.org/viewtopic.php?f=46&t=21666/`
..to raise awareness of it.
