### ISSUE TITLE
pcmag.com Zergnet promoted stories

### ISSUE THREAD

**Issue by terrorist96** [uBlockOrigin/uAssets#546]
### URL(s) where the issue occurs

`http://www.pcmag.com/article2/0,2817,2500086,00.asp`

### Describe the issue

Promoted stories Zergnet at bottom

**Comment by gorhill** [comment]
It's full of EasyList filter exceptions on that site. It seems the site is no longer using Instart Logic, so it would be nice to see the exceptions removed for `pcmag.com`.

fyi @ryanbr

**Comment by okiehsch** [comment]
`uk.pcmag.com` still uses Instart Logic.

**Comment by gorhill** [comment]
> `uk.pcmag.com` still uses Instart Logic.

Do the exception filters accomplish anything useful for that site?

**Comment by okiehsch** [comment]
They never do :), but this site also circumvents uBO-extra, I get redirected.

**Comment by gorhill** [comment]
How about:

    ||www.pcmag.com^$csp=default-src *.pcmag.com 'unsafe-inline' 'unsafe-eval' data: blob: disqus.com disquscdn.com facebook.com fonts.googleapis.com pinterest.com reddit.com zdbb.net ziffstatic.com

This way no need to tediously hunt all exception filters.

**Comment by okiehsch** [comment]
Works for me.

**Comment by gorhill** [comment]
Needs fine tuning though, subdomains issues.

**Comment by gorhill** [comment]
Imrpoved:

`||www.pcmag.com^$csp=default-src 'self' *.pcmag.com 'unsafe-inline' 'unsafe-eval' data: blob: bootstrapcdn.com *.bootstrapcdn.com disqus.com *.disqus.com disquscdn.com *.disquscdn.com facebook.com *.facebook.com googleapis.com *.googleapis.com pinterest.com *.pinterest.com reddit.com *.reddit.com youtube.com *.youtube.com zdbb.net *.zdbb.net ziffstatic.com *.ziffstatic.com`

**Comment by yourduskquibbles** [comment]
Will this filter also work for 'uk.pcmag.com' when it is starting with 'www'.? 

When I use 'www.uk.pcmag.com' I get redirected to 'uk.pcmag.com' with no 'www' in the URL.

**Comment by okiehsch** [comment]
Works without any issues I can see.

**Comment by okiehsch** [comment]
@yourduskquibbles no you would have to use 
`||pcmag.com^$csp=whatever` if you want the csp in `pcmag.com` and `uk.pcmag.com`, or
`||www.pcmag.com^$csp` and `||uk.pcmag.com^$csp` if you want it in only one of the two.

**Comment by gorhill** [comment]
How does that work for `uk.pcmag.com`:

`||pcmag.com^$csp=default-src http://*.pcmag.com 'unsafe-inline' 'unsafe-eval' data: blob: bootstrapcdn.com *.bootstrapcdn.com disqus.com *.disqus.com disquscdn.com *.disquscdn.com facebook.com *.facebook.com googleapis.com *.googleapis.com http://*.ign.com pinterest.com *.pinterest.com reddit.com *.reddit.com youtube.com *.youtube.com zdbb.net *.zdbb.net ziffdavisinternet.com *.ziffdavisinternet.com ziffstatic.com *.ziffstatic.com`

**Comment by yourduskquibbles** [comment]
Seems like 'http://' should not be included if the requests are to 'https://' version of 'pcmag.com' or 'ign.com', no?

**Comment by gorhill** [comment]
The page requests mixed contents, the browser will properly block if that mixed content is active (javascript, etc). Using `http` in a CSP is equivalent to stating `http` or `https`. If I do not use `http`, there are pages with broken images, because the site explicitly pulls from some `http://....pcmag.com/...`

**Comment by yourduskquibbles** [comment]
Makes sense to me then, I wasn't aware csp will treat 'http://' that way. Thanks!

**Comment by gorhill** [comment]
For any breakage, I will modify the CSP accordingly.

**Comment by okiehsch** [comment]
The only slight breakage I can see is at the bottom of every `uk,pcmag.com` site.
![unnt](https://user-images.githubusercontent.com/16838044/28346307-6e0be2b4-6c30-11e7-93e2-8a0ccd485420.PNG)

adding `*.truste.com` on my end.

**Comment by okiehsch** [comment]
@gorhill by the way the reason I sometimes get IL-redirections at `uk.pcmag.com` with uBO-extra
enabled is that I get randomly served two different documents.
1. The "normal" on triggering the redirection via inline-script.
![il2](https://user-images.githubusercontent.com/16838044/28346986-bc863058-6c34-11e7-958e-95aca7c053ee.PNG)
this one is fixed by uBO-extra.
2. A different one triggering the redirection via` http://uk.pcmag.com/i10c@p1/client/latest/abd/instart.js`
![il](https://user-images.githubusercontent.com/16838044/28347027-f81b4ce8-6c34-11e7-9437-99f342e2c1fa.PNG)
this one can simply be fixed by blocking `uk.pcmag.com/i10c@p1/client/latest/abd/instart.js`.

**Comment by terrorist96** [comment]
@gorhill @okiehsch I still see the promoted content. Here's a small taste of the log: 
![image](https://user-images.githubusercontent.com/12802056/28347380-b4a600b4-6c04-11e7-85bf-5e739b323cf5.png)
Looks like the newly added filter is catching some stuff but not everything?

**Comment by terrorist96** [comment]
And the site never seems to truly finish loading. Here's what it looks like after letting it sit for a few minutes:
![image](https://user-images.githubusercontent.com/12802056/28347434-06c956ac-6c05-11e7-9a85-b38c1338db01.png)
and of course the ads that are still unblocked:
![image](https://user-images.githubusercontent.com/12802056/28347446-16eb990a-6c05-11e7-8a61-44ad056bb826.png)

**Comment by okiehsch** [comment]
The site uses Instart Logic  same as your `msn.com` issue https://github.com/uBlockOrigin/uAssets/issues/506.

**Comment by gotitbro** [comment]
@okiehsch @gorhill **Zergnet** should be blocked in uBO filters. It is the same as **Outbrain, Taboola etc.** which are already blocked by the default filters in uBO.
