### ISSUE TITLE
bullet screen does not display

### ISSUE THREAD

**Issue by realhuyang** [uBlockOrigin/uAssets#7136]
### URL(s) where the issue occurs

`https://www.iqiyi.com/v_19rvqiz3l8.html`

### Describe the issue

[`iqiyi.com` does not display a bullet screen when uBlock Origin is turned on.]

### Screenshot(s)

[]

### Versions

- Browser/version: [ Chrome 80.0.3987.149]
- uBlock Origin version: [v1.24.4]

### Settings

- [default setting]

### Notes

[By default, ads can be blocked but no bullet screen is displayed.]

**Comment by mapx-** [comment]
Provide screenshots with / without uBO enabled, steps (If I click the green button in the middle wants to download an `exe` etc), we don't read Chinese

**Comment by realhuyang** [comment]
1. Turn on the bullet screen switch, close UBO,the bullet screen display normally
![Snipaste_2020-03-22_19-42-07](https://user-images.githubusercontent.com/25172023/77248903-245a6280-6c78-11ea-9b7c-35ea334d228f.png)

2.Turn on the bullet screen switch, turn on UBO, the bullet screen is not displayed
![Snipaste_2020-03-22_19-29-51](https://user-images.githubusercontent.com/25172023/77248905-2b817080-6c78-11ea-9aaa-c856e2d7b7f1.png)

**Comment by mapx-** [comment]
- I got the video running only using a chinese ip
- I get only the first 3 buttons at the bottom, I guess I need an account to reproduce that "bullet" thing

![image](https://user-images.githubusercontent.com/10303732/77249860-3e7a4d80-6c44-11ea-803c-888f30c26d56.png)

**Comment by realhuyang** [comment]
● I just tried it and did n’t log in.
● I tested it with the IPs in the US, London and Singapore, and they all showed normal.
![Snipaste_2020-03-22_21-03-06](https://user-images.githubusercontent.com/25172023/77250244-8ec3d080-6c81-11ea-86de-e12b37a88dcc.png)

● You can log in with my account, I will send you a password, my email: 879625424@qq.com, you can contact me

**Comment by krystian3w** [comment]
Disable any AdGuard Annoyance / Fanboy Annoyance and try again?

**Comment by krystian3w** [comment]
Code for bullets

```html
<div id="qyBarrageVue" style="" class="qy-barrage qy-barrage-v1">
    <div class="barrage-switch-wrap"><span class="barrage-switch" data-barrage-status="show"><i title="关闭弹幕" class="qyb-svg qyb-svg-on" rseat="140742_cls"><svg aria-hidden="true" alt="" class="qyb-symbol-icon"><use xlink:href="#qyb-on"></use></svg><div class="qy-barrage-tooltip">关闭弹幕</div></i><i title="开启弹幕" class="qyb-svg qyb-svg-off" rseat="140743_opn"><svg aria-hidden="true" alt="" class="qyb-symbol-icon"><use xlink:href="#qyb-off"></use></svg><div class="qy-barrage-tooltip">开启弹幕</div></i></span>
        <div class="barrage-icons switch-tips" style="display: none;" data-barrage-btntip="wrap"></div>
        <div class="qy-barrage-redbag-tips" data-barrage-hb="tip" style="width: 510px; display: none;">
            <div class="hb_tipBox_inner">
                <div class="barrage-icons hb_tipBox_left">l</div>
                <div class="hb_tipBox_con">
                    <p class="hbdm_ygTxt" data-barrage-hb="tipcon"></p>
                    <a href="javascript:void(0)" data-barrage-hb="tipclose" class="barrage-icons hbdm_ygLink"></a>
                </div>
                <div class="barrage-icons hb_tipBox_right"></div>
                <div class="barrage-icons hbdm_arr"></div>
            </div>
        </div>
    </div>
    <div class="barrage-set-wrap" data-barrage-panel="config"><a href="javascript:void(0);" title="弹幕播放设置" data-barrage-config="config" class="barrage-set-icon"><i class="qyb-svg qyb-svg-setting"><svg aria-hidden="true" class="qyb-symbol-icon"><use xlink:href="#qyb-setting"></use></svg></i><div class="qy-barrage-tooltip">弹幕播放设置</div></a>
        <div class="qy-barrage-set dn" data-barrage-panel="panel"></div>
        <div class="qy-barrage-shiel dn" data-barrage-module="custom"></div>
    </div>
    <div class="barrage-list-wrap dn" data-barrage-list="btn" rseat="80521_listbox_danmu_open"><i title="弹幕列表" class="qyb-svg qyb-svg-list"><svg aria-hidden="true" class="qyb-symbol-icon"><use xlink:href="#qyb-list"></use></svg></i>
        <div class="qy-barrage-tooltip">弹幕列表</div>
    </div>
    <div class="barrage-input-wrap nlogin" data-barrage-ele="wrap">
        <div class="barrage-input-box barrage-input-role" data-barrage-wrap="input">
            <div class="barrage-role">
                <div class="role-setting-entry j_role_btn" title="弹幕发送设置"><i class="qyb-svg qyb-svg-A j_textrole_widget"><svg aria-hidden="true" class="qyb-symbol-icon"><use xlink:href="#qyb-A"></use></svg></i><i class="qyb-svg qyb-svg-role j_clickrole_widget dn"><svg aria-hidden="true" class="qyb-symbol-icon"><use xlink:href="#qyb-role"></use></svg></i><i class="role-entry j_role_widget dn"></i>
                    <div class="qy-barrage-tooltip">弹幕发送设置</div>
                </div>
                <div class="qy-barrage-role j_roleList_panel dn">
                    <div class="barrageSet_fsBox" data-barrage-content="contentColor">
                        <p class="role-title">色彩</p>
                        <div class="color-box"><a href="javascript:void(0)" data-barrage-color="FFFFFF" data-rseat="608241_color_1" class="color-wrap selected"><i class="color-inner color-white"></i></a><a href="javascript:void(0)" data-barrage-color="FEF102" data-rseat="608241_color_4" class="color-wrap"><i class="color-inner color-yellow"></i> </a><a data-barrage-color="00FF10" href="javascript:void(0)" data-rseat="608241_color_6" class="color-wrap"><i class="color-inner color-green"></i> </a><a data-barrage-color="FF3E3E" href="javascript:void(0)" data-rseat="608241_color_2" class="color-wrap"><i class="color-inner color-red"></i> </a><a data-barrage-color="D8B67E" href="javascript:void(0)" data-rseat="608241_color_13" title="VIP登录解锁暗金色" class="color-wrap vip"><i class="color-inner color-vip"></i> <i class="barrage-icons color-vip-icon" data-barrage-vipicon=""></i> <i class="barrage-icons color-vip-tit"></i></a></div>
                    </div>
                </div>
            </div>
            <input type="text" placeholder="弹幕走一波…" class="barrage-input" data-barrage-input="barrage" data-rseat="608241_input" disabled="disabled">
        </div><a href="javascript:;" data-barrage-send="barrage" data-barrage-limit="barrage" class="barrage-send">发送</a>
        <div class="barrage-login" data-barrage-login="" id="danmuLogin">
            <p class="barrage-login-info"><a href="javascript:void(0)" class="login-link">登录</a><a href="javascript:void(0)" data-barrage-reg="" class="login-link dn">注册</a>说⼀句～</p>
        </div>
    </div>
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="qyb-A" viewBox="0 0 1024 1024">
            <path d="M139.597 935.667l320.292-833.989h118.892l341.316 833.99H794.374L697.09 683.055H348.359l-91.565 252.611H139.597zM380.24 593.185h282.744l-87.063-230.951c-26.532-70.17-46.286-127.789-59.155-172.962a1060.386 1060.386 0 0 1-44.961 159.298L380.24 593.185z"></path>
        </symbol>
        <symbol id="qyb-close" viewBox="0 0 1024 1024">
            <path d="M622.277 512l378.092-378.092c31.508-31.508 31.508-78.77 0-110.277-31.507-31.508-78.769-31.508-110.277 0L512 401.723 133.908 23.631C102.4-7.877 55.138-7.877 23.63 23.63c-31.508 31.507-31.508 78.769 0 110.277L401.723 512 23.631 890.092c-31.508 31.508-31.508 78.77 0 110.277 31.507 31.508 78.769 31.508 110.277 0L512 622.277l378.092 378.092c31.508 31.508 78.77 31.508 110.277 0 31.508-31.507 31.508-78.769 0-110.277L622.277 512z"></path>
        </symbol>
        <symbol id="qyb-l-arr" viewBox="0 0 1024 1024">
            <path d="M652.459 968.875L195.669 512 652.46 55.125l60.416 60.416L316.33 512l396.544 396.459z"></path>
        </symbol>
        <symbol id="qyb-list" viewBox="0 0 1024 1024">
            <path d="M768 1024H256c-130.327 0-232.727-102.4-232.727-232.727V232.727C23.273 102.4 125.673 0 256 0h512c130.327 0 232.727 102.4 232.727 232.727v558.546C1000.727 921.6 898.327 1024 768 1024zM256 93.09c-79.127 0-139.636 60.51-139.636 139.637v558.546c0 79.127 60.509 139.636 139.636 139.636h512c79.127 0 139.636-60.509 139.636-139.636V232.727c0-79.127-60.509-139.636-139.636-139.636H256z"></path>
            <path d="M768 418.91H442.182c-23.273 0-46.546-18.62-46.546-46.546 0-23.273 18.619-46.546 46.546-46.546H768c23.273 0 46.545 18.618 46.545 46.546S795.927 418.909 768 418.909zm-93.09 218.763H256c-23.273 0-46.545-18.618-46.545-46.546 0-23.272 18.618-46.545 46.545-46.545h418.91c23.272 0 46.545 18.618 46.545 46.545s-18.619 46.546-46.546 46.546zM209.45499999999998 372.364a46.545 46.545 0 1 0 93.09 0 46.545 46.545 0 1 0-93.09 0z"></path>
        </symbol>
        <symbol id="qyb-off" viewBox="0 0 1152 1024">
            <path d="M311.467 661.333c0 4.267-4.267 8.534-8.534 12.8 0 4.267 0 4.267-4.266 8.534h-12.8c-4.267 0-8.534-4.267-17.067-8.534-8.533-8.533-17.067-8.533-25.6-8.533-8.533 0-12.8 4.267-17.067 12.8-4.266 12.8-8.533 21.333-4.266 29.867 4.266 8.533 12.8 17.066 25.6 21.333 17.066 8.533 34.133 17.067 46.933 17.067 12.8 0 21.333-4.267 34.133-8.534 8.534-4.266 17.067-17.066 25.6-29.866 8.534-12.8 12.8-34.134 17.067-55.467 4.267-21.333 4.267-51.2 4.267-85.333 0-12.8 0-21.334-4.267-29.867 0-8.533-4.267-12.8-8.533-17.067-4.267-4.266-8.534-8.533-12.8-8.533-4.267 0-12.8-4.267-21.334-4.267h-55.466s-4.267-4.266 0-8.533l4.266-38.4c0-4.267 0-8.533 4.267-8.533h46.933c17.067 0 25.6-4.267 34.134-12.8 8.533-8.534 12.8-21.334 12.8-42.667v-72.533c0-17.067-4.267-34.134-8.534-42.667-12.8-12.8-25.6-17.067-42.666-17.067H243.2c-8.533 0-17.067 0-21.333 4.267-4.267 8.533-4.267 12.8-4.267 25.6 0 8.533 0 17.067 4.267 21.333 4.266 4.267 12.8 8.534 21.333 8.534h64c4.267 0 8.533 0 8.533 4.266v34.134c0 8.533 0 12.8-4.266 12.8s0 4.266-4.267 4.266h-38.4c-8.533 0-12.8 0-21.333 4.267-4.267 0-8.534 4.267-8.534 4.267-4.266 4.266-8.533 12.8-8.533 17.066 0 8.534-4.267 17.067-4.267 25.6l-8.533 72.534v29.866c0 8.534 4.267 12.8 8.533 17.067 4.267 4.267 8.534 4.267 17.067 8.533h68.267c4.266 0 8.533 0 8.533 4.267s4.267 8.533 4.267 17.067c0 21.333 0 42.666-4.267 55.466 0 8.534-4.267 21.334-8.533 25.6zM896 486.4c-93.867 0-174.933 51.2-217.6 123.733H571.733V576H640c21.333 0 34.133-4.267 42.667-12.8 8.533-8.533 12.8-21.333 12.8-42.667V358.4c0-21.333-4.267-34.133-12.8-42.667-8.534-8.533-21.334-12.8-42.667-12.8 0-4.266 4.267-4.266 4.267-8.533-4.267 0-4.267-4.267-4.267-4.267 4.267-12.8 8.533-21.333 4.267-25.6 0-8.533-4.267-12.8-12.8-21.333-8.534-4.267-17.067-4.267-21.334-4.267-8.533 4.267-12.8 8.534-21.333 21.334-4.267 8.533-8.533 12.8-12.8 21.333-4.267 8.533-8.533 12.8-12.8 21.333H512c-4.267-8.533-8.533-17.066-8.533-21.333-4.267-8.533-8.534-12.8-12.8-21.333-4.267-12.8-12.8-17.067-21.334-17.067s-17.066 0-25.6 8.533c-8.533 8.534-12.8 12.8-12.8 21.334s0 17.066 8.534 25.6l4.266 4.266L448 307.2c-17.067 0-29.867 4.267-38.4 12.8-8.533 4.267-12.8 21.333-12.8 38.4v157.867c0 21.333 4.267 34.133 12.8 42.666 8.533 8.534 21.333 12.8 42.667 12.8H512v34.134h-98.133c-12.8 0-21.334 0-25.6 4.266-4.267 4.267-8.534 8.534-8.534 21.334v17.066c0 4.267 4.267 8.534 4.267 8.534 4.267 0 4.267 4.266 8.533 4.266H512V716.8c0 12.8 4.267 21.333 8.533 25.6 4.267 4.267 12.8 8.533 21.334 8.533 12.8 0 21.333-4.266 25.6-8.533 4.266-4.267 4.266-12.8 4.266-25.6v-55.467H652.8c-8.533 25.6-12.8 51.2-12.8 76.8 0 140.8 115.2 256 256 256s256-115.2 256-256S1036.8 486.4 896 486.4zm-328.533-128h55.466c4.267 0 4.267 0 4.267 4.267V409.6h-59.733v-51.2zm0 102.4H627.2V512h-55.467v-51.2zM512 516.267h-55.467v-51.2H512v51.2zm0-102.4h-59.733V362.667H512v51.2zM725.333 742.4c0-93.867 76.8-170.667 170.667-170.667 29.867 0 59.733 8.534 85.333 25.6L746.667 832c-12.8-29.867-21.334-59.733-21.334-89.6zM896 913.067c-29.867 0-59.733-8.534-85.333-25.6L1045.333 652.8c17.067 25.6 25.6 55.467 25.6 85.333-4.266 98.134-81.066 174.934-174.933 174.934z"></path>
            <path d="M580.267 878.933H213.333c-72.533 0-128-55.466-128-119.466V230.4c0-64 55.467-119.467 128-119.467h512c72.534 0 128 55.467 128 119.467v140.8c0 25.6 17.067 42.667 42.667 42.667s42.667-17.067 42.667-42.667V230.4c0-115.2-93.867-204.8-213.334-204.8h-512C93.867 25.6 0 119.467 0 230.4v529.067c0 115.2 93.867 204.8 213.333 204.8h366.934c25.6 0 42.666-17.067 42.666-42.667s-21.333-42.667-42.666-42.667z"></path>
        </symbol>
        <symbol id="qyb-on" viewBox="0 0 1152 1024">
            <path d="M311.467 661.333c0 4.267-4.267 8.534-8.534 12.8 0 4.267 0 4.267-4.266 8.534h-12.8c-4.267 0-8.534-4.267-17.067-8.534-8.533-8.533-17.067-8.533-25.6-8.533-8.533 0-12.8 4.267-17.067 12.8-4.266 12.8-8.533 21.333-4.266 29.867 4.266 8.533 12.8 17.066 25.6 21.333 17.066 8.533 34.133 17.067 46.933 17.067 12.8 0 21.333-4.267 34.133-8.534 8.534-4.266 17.067-17.066 25.6-29.866 8.534-12.8 12.8-34.134 17.067-55.467 4.267-21.333 4.267-51.2 4.267-85.333 0-12.8 0-21.334-4.267-29.867 0-8.533-4.267-12.8-8.533-17.067-4.267-4.266-8.534-8.533-12.8-8.533-4.267 0-12.8-4.267-21.334-4.267h-55.466s-4.267-4.266 0-8.533l4.266-38.4c0-4.267 0-8.533 4.267-8.533h46.933c17.067 0 25.6-4.267 34.134-12.8 8.533-8.534 12.8-21.334 12.8-42.667v-72.533c0-17.067-4.267-34.134-8.534-42.667-12.8-12.8-25.6-17.067-42.666-17.067H243.2c-8.533 0-17.067 0-21.333 4.267-4.267 8.533-4.267 12.8-4.267 25.6 0 8.533 0 17.067 4.267 21.333 4.266 4.267 12.8 8.534 21.333 8.534h64c4.267 0 8.533 0 8.533 4.266v34.134c0 8.533 0 12.8-4.266 12.8 0 0-4.267 4.266-8.534 4.266H268.8c-8.533 0-12.8 0-21.333 4.267-4.267 0-8.534 4.267-8.534 4.267-4.266 4.266-8.533 12.8-8.533 17.066 0 8.534-4.267 17.067-4.267 25.6l-8.533 72.534v29.866c0 8.534 4.267 12.8 8.533 17.067 4.267 4.267 8.534 4.267 17.067 8.533h68.267c4.266 0 8.533 0 8.533 4.267s4.267 8.533 4.267 17.067c0 21.333 0 42.666-4.267 55.466 0 8.534-4.267 21.334-8.533 25.6zM896 486.4c-93.867 0-174.933 51.2-217.6 123.733H571.733V576H640c21.333 0 34.133-4.267 42.667-12.8 8.533-8.533 12.8-21.333 12.8-42.667V358.4c0-21.333-4.267-34.133-12.8-42.667-8.534-8.533-21.334-12.8-42.667-12.8 0-4.266 4.267-4.266 4.267-8.533-4.267 0-4.267-4.267-4.267-4.267 4.267-12.8 8.533-21.333 4.267-25.6 0-8.533-4.267-12.8-12.8-21.333-8.534-4.267-17.067-4.267-21.334-4.267-8.533 4.267-12.8 8.534-21.333 21.334-4.267 8.533-8.533 12.8-12.8 21.333-4.267 8.533-8.533 12.8-12.8 21.333H512c-4.267-8.533-8.533-17.066-8.533-21.333-4.267-8.533-8.534-12.8-12.8-21.333-4.267-12.8-12.8-17.067-21.334-17.067s-17.066 0-25.6 8.533c-8.533 8.534-12.8 12.8-12.8 21.334s0 17.066 8.534 25.6l4.266 4.266L448 307.2c-17.067 0-29.867 4.267-38.4 12.8-8.533 4.267-12.8 21.333-12.8 38.4v157.867c0 21.333 4.267 34.133 12.8 42.666 8.533 8.534 21.333 12.8 42.667 12.8H512v34.134h-98.133c-12.8 0-21.334 0-25.6 4.266-4.267 4.267-8.534 8.534-8.534 21.334v17.066c0 4.267 4.267 8.534 4.267 8.534 4.267 0 4.267 4.266 8.533 4.266H512V716.8c0 12.8 4.267 21.333 8.533 25.6 4.267 4.267 12.8 8.533 21.334 8.533 12.8 0 21.333-4.266 25.6-8.533 4.266-4.267 4.266-12.8 4.266-25.6v-55.467H652.8c-8.533 25.6-12.8 51.2-12.8 76.8 0 140.8 115.2 256 256 256s256-115.2 256-256S1036.8 486.4 896 486.4zm-328.533-128h55.466c4.267 0 4.267 0 4.267 4.267V409.6h-59.733v-51.2zm0 102.4H627.2V512h-55.467v-51.2zM512 516.267h-55.467v-51.2H512v51.2zm0-102.4h-59.733V362.667H512v51.2zm384 499.2c-93.867 0-170.667-76.8-170.667-170.667S802.133 571.733 896 571.733s170.667 76.8 170.667 170.667S989.867 913.067 896 913.067z"></path>
            <path d="M951.467 669.867L878.933 742.4l-29.866-25.6C832 699.733 806.4 704 789.333 721.067c-17.066 17.066-12.8 42.666 4.267 59.733l59.733 51.2c8.534 8.533 17.067 8.533 29.867 8.533s21.333-4.266 29.867-12.8l102.4-102.4c17.066-17.066 17.066-42.666 0-59.733-21.334-12.8-46.934-12.8-64 4.267zm-371.2 209.066H213.333c-72.533 0-128-55.466-128-119.466V230.4c0-64 55.467-119.467 128-119.467h512c72.534 0 128 55.467 128 119.467v140.8c0 25.6 17.067 42.667 42.667 42.667s42.667-17.067 42.667-42.667V230.4c0-115.2-93.867-204.8-213.334-204.8h-512C93.867 25.6 0 119.467 0 230.4v529.067c0 115.2 93.867 204.8 213.333 204.8h366.934c25.6 0 42.666-17.067 42.666-42.667s-21.333-42.667-42.666-42.667z"></path>
        </symbol>
        <symbol id="qyb-palette" viewBox="0 0 1024 1024">
            <path d="M496.742 887.467c-236.27 0-428.475-168.448-428.475-375.467S260.47 136.533 496.742 136.533c236.271 0 428.476 168.448 428.476 375.467 0 25.395-7.543 45.5-22.425 59.802-25.362 24.37-62.02 22.937-94.447 21.606-39.493-1.707-51.03.444-54.34 9.387-7.373 19.9-1.161 30.686 13.516 53.248 15.975 24.507 40.107 61.542 13.653 111.65-46.557 88.303-177.459 119.774-284.433 119.774zm0-682.667c-198.621 0-360.209 137.83-360.209 307.2 0 169.404 161.588 307.2 360.21 307.2 107.724 0 197.802-33.485 224.05-83.354 7.1-13.448 4.745-19.217-10.478-42.496-15.906-24.405-39.902-61.235-20.412-114.176 21.436-58.026 81.579-55.535 121.14-53.999 13.652.547 39.116 1.57 44.44-2.662-.033 0 1.434-2.662 1.434-10.547 0-169.336-161.587-307.166-360.175-307.166z"></path>
            <path d="M382.26 329.148a38.161 36.557 0 1 0 76.321 0 38.161 36.557 0 1 0-76.322 0zM255.044 426.667a38.161 36.557 0 1 0 76.322 0 38.161 36.557 0 1 0-76.322 0zM255.044 585.148a50.893 48.777 0 1 0 101.786 0 50.893 48.777 0 1 0-101.786 0zM433.118 682.667a50.893 48.777 0 1 0 101.785 0 50.893 48.777 0 1 0-101.785 0z"></path>
        </symbol>
        <symbol id="qyb-palette-shield" viewBox="0 0 1024 1024">
            <path d="M919.586 451.038a34.133 34.133 0 0 1-67.106 12.493C825.07 316.245 675.26 204.8 496.742 204.8c-199.953 0-360.209 138.718-360.209 307.2s160.256 307.2 360.21 307.2c28.262 0 56.149-2.321 82.26-6.93a34.133 34.133 0 1 1 11.81 67.244 547.499 547.499 0 0 1-94.07 7.953C261.12 887.467 68.266 720.555 68.266 512S261.12 136.533 496.742 136.533c209.955 0 389.12 133.291 422.844 314.505zM420.42 365.705c-21.094 0-38.16-16.384-38.16-36.557 0-20.207 17.066-36.591 38.16-36.591 21.06 0 38.161 16.384 38.161 36.59 0 20.208-17.066 36.558-38.16 36.558zm-127.215 97.518c-21.06 0-38.16-16.384-38.16-36.556 0-20.207 17.066-36.557 38.16-36.557 21.095 0 38.161 16.384 38.161 36.557 0 20.207-17.066 36.556-38.16 36.556zm12.732 170.667c-28.126 0-50.893-21.845-50.893-48.742 0-26.966 22.767-48.777 50.859-48.777 28.126 0 50.893 21.846 50.893 48.777s-22.767 48.742-50.859 48.742zm178.074 97.553c-28.092 0-50.859-21.845-50.859-48.776s22.767-48.777 50.859-48.777 50.858 21.845 50.858 48.777-22.767 48.776-50.858 48.776z"></path>
            <path d="M747.281 777.899a102.4 102.4 0 0 0 125.85-147.456L747.28 777.899zm-51.439-44.92l124.894-146.33a102.4 102.4 0 0 0-124.86 146.33zm89.225 120.354a170.667 170.667 0 1 1 0-341.333 170.667 170.667 0 0 1 0 341.333z"></path>
        </symbol>
        <symbol id="qyb-palette-shield1" viewBox="0 0 1024 1024">
            <path d="M919.586 451.038a34.133 34.133 0 0 1-67.106 12.493C825.07 316.245 675.26 204.8 496.742 204.8c-199.953 0-360.209 138.718-360.209 307.2s160.256 307.2 360.21 307.2c28.262 0 56.149-2.321 82.26-6.93a34.133 34.133 0 1 1 11.81 67.244 547.499 547.499 0 0 1-94.07 7.953C261.12 887.467 68.266 720.555 68.266 512S261.12 136.533 496.742 136.533c209.955 0 389.12 133.291 422.844 314.505zM420.42 365.705c-21.094 0-38.16-16.384-38.16-36.557 0-20.207 17.066-36.591 38.16-36.591 21.06 0 38.161 16.384 38.161 36.59 0 20.208-17.066 36.558-38.16 36.558zm-127.215 97.518c-21.06 0-38.16-16.384-38.16-36.556 0-20.207 17.066-36.557 38.16-36.557 21.095 0 38.161 16.384 38.161 36.557 0 20.207-17.066 36.556-38.16 36.556zm12.732 170.667c-28.126 0-50.893-21.845-50.893-48.742 0-26.966 22.767-48.777 50.859-48.777 28.126 0 50.893 21.846 50.893 48.777s-22.767 48.742-50.859 48.742zm178.074 97.553c-28.092 0-50.859-21.845-50.859-48.776s22.767-48.777 50.859-48.777 50.858 21.845 50.858 48.777-22.767 48.776-50.858 48.776z"></path>
        </symbol>
        <symbol id="qyb-palette-shield2" viewBox="0 0 1024 1024">
            <path d="M785.067 853.333c-94.106 0-170.667-76.56-170.667-170.666S690.961 512 785.067 512s170.666 76.561 170.666 170.667-76.56 170.666-170.666 170.666zm0-273.066c-56.457 0-102.4 45.943-102.4 102.4s45.943 102.4 102.4 102.4 102.4-45.944 102.4-102.4-45.944-102.4-102.4-102.4z" fill="#FF5858"></path>
            <path d="M690.859 738.85l148.65-174.148 51.917 44.34-148.65 174.113z" fill="#FF5858"></path>
        </symbol>
        <symbol id="qyb-r-arr" viewBox="0 0 1024 1024">
            <path d="M371.541 55.125L828.331 512 371.54 968.875l-60.416-60.416L707.67 512 311.125 115.541z"></path>
        </symbol>
        <symbol id="qyb-refresh" viewBox="0 0 1024 1024">
            <path d="M911.653 365.568H658.286a36.571 36.571 0 0 1 0-73.143H875.08V73.143a36.571 36.571 0 0 1 73.143 0v255.854a36.571 36.571 0 0 1-36.571 36.571z"></path>
            <path d="M512 987.429C249.856 987.429 36.571 774.144 36.571 512S249.856 36.571 512 36.571a474.112 474.112 0 0 1 422.473 257.17 36.571 36.571 0 0 1-65.024 33.646A401.042 401.042 0 0 0 512 109.714 402.725 402.725 0 0 0 109.714 512c0 221.77 180.444 402.286 402.286 402.286a400.603 400.603 0 0 0 359.131-220.819 36.571 36.571 0 1 1 65.317 32.988A473.6 473.6 0 0 1 512 987.429z"></path>
        </symbol>
        <symbol id="qyb-role" viewBox="0 0 1024 1024">
            <path d="M873.387 810.667H725.46L686.72 901.12a42.667 42.667 0 1 1-78.464-33.621l152.192-355.286c14.805-34.56 63.744-34.474 78.507.043L990.42 867.584a42.667 42.667 0 0 1-78.464 33.45l-38.528-90.367zm-36.352-85.334l-37.419-87.765-37.632 87.765h75.05zM336.128 393.387a42.667 42.667 0 0 1 84.224-13.398 64 64 0 0 0 126.421 0 42.667 42.667 0 1 1 84.267 13.355 149.333 149.333 0 0 1-294.955.085zm-215.253 11.946a362.667 362.667 0 0 1 721.28-54.4 42.667 42.667 0 1 1-84.352 12.715 277.419 277.419 0 0 0-551.595 41.685c0 89.003 42.197 170.923 112.341 222.934a42.667 42.667 0 0 1 7.68 61.184L200.576 844.075h274.432a42.667 42.667 0 0 1 0 85.333H200.533a85.333 85.333 0 0 1-66.218-139.179l99.242-122.069a361.856 361.856 0 0 1-112.682-262.827z"></path>
        </symbol>
        <symbol id="qyb-setting" viewBox="0 0 1152 1024">
            <path d="M554.667 972.8H213.333C93.867 972.8 0 878.933 0 768V238.933c0-115.2 93.867-204.8 213.333-204.8h486.4c119.467 0 213.334 93.867 213.334 204.8v115.2c0 25.6-17.067 42.667-42.667 42.667s-42.667-17.067-42.667-42.667v-115.2c0-68.266-55.466-119.466-128-119.466h-486.4c-68.266 0-128 51.2-128 119.466V768c0 68.267 55.467 119.467 128 119.467h341.334c25.6 0 42.666 17.066 42.666 42.666S580.267 972.8 554.667 972.8z"></path>
            <path d="M1105.067 674.133h-21.334c-4.266-25.6-17.066-51.2-29.866-72.533l17.066-17.067c17.067-17.066 17.067-42.666 0-59.733-17.066-17.067-42.666-17.067-59.733 0l-17.067 17.067C972.8 529.067 947.2 516.267 921.6 512v-21.333c0-25.6-21.333-42.667-42.667-42.667-25.6 0-42.666 21.333-42.666 42.667V512c-25.6 4.267-51.2 17.067-72.534 29.867L746.667 524.8c-17.067-17.067-42.667-17.067-59.734 0-17.066 17.067-17.066 42.667 0 59.733L704 601.6c-17.067 25.6-25.6 59.733-29.867 89.6H652.8c-25.6 0-42.667 21.333-38.4 46.933 0 21.334 21.333 42.667 42.667 38.4h29.866c4.267 17.067 12.8 34.134 21.334 46.934l-21.334 29.866c-17.066 17.067-17.066 42.667 0 59.734 8.534 8.533 21.334 12.8 29.867 12.8 12.8 0 21.333-4.267 29.867-12.8L768 896c21.333 12.8 46.933 25.6 72.533 29.867V947.2c0 25.6 21.334 42.667 42.667 42.667 25.6 0 42.667-21.334 42.667-42.667v-21.333c25.6-4.267 51.2-17.067 72.533-29.867l17.067 17.067c8.533 8.533 21.333 12.8 29.866 12.8 12.8 0 21.334-4.267 29.867-12.8 17.067-17.067 17.067-42.667 0-59.734l-17.067-17.066c12.8-21.334 25.6-46.934 29.867-72.534h25.6c25.6 0 42.667-21.333 38.4-46.933 0-25.6-21.333-42.667-46.933-42.667zM883.2 853.333c-72.533 0-132.267-59.733-132.267-132.266S810.667 588.8 883.2 588.8c72.533 0 132.267 59.733 132.267 132.267S955.733 853.333 883.2 853.333z"></path>
            <path d="M844.8 721.067a42.667 42.667 0 1 0 85.333 0 42.667 42.667 0 1 0-85.333 0zM635.733 520.533h-409.6c-25.6 0-42.666-17.066-42.666-42.666s17.066-42.667 42.666-42.667h405.334c25.6 0 42.666 17.067 42.666 42.667 4.267 21.333-17.066 42.666-38.4 42.666zm-362.666-179.2h-38.4c-25.6 0-42.667-17.066-42.667-42.666S209.067 256 234.667 256h38.4c25.6 0 42.666 17.067 42.666 42.667s-17.066 42.666-42.666 42.666zm409.6 0H405.333c-25.6 0-42.666-17.066-42.666-42.666S379.733 256 405.333 256h277.334c25.6 0 42.666 17.067 42.666 42.667S704 341.333 682.667 341.333z"></path>
        </symbol>
        <symbol id="qyb-feedback" viewBox="0 0 1024 1024">
            <path d="M597.76 0v85.333H170.667a85.333 85.333 0 0 0-85.334 85.334v682.666a85.333 85.333 0 0 0 85.334 85.334h682.666a85.333 85.333 0 0 0 85.334-85.334V425.9H1024v427.434A170.667 170.667 0 0 1 853.333 1024H170.667A170.667 170.667 0 0 1 0 853.333V170.667A170.667 170.667 0 0 1 170.667 0H597.76zM1024 425.899v427.434A170.667 170.667 0 0 1 853.333 1024H170.667A170.667 170.667 0 0 1 0 853.333V170.667A170.667 170.667 0 0 1 170.667 0H597.76a42.667 42.667 0 0 1 0 85.333H170.667a85.333 85.333 0 0 0-85.334 85.334v682.666a85.333 85.333 0 0 0 85.334 85.334h682.666a85.333 85.333 0 0 0 85.334-85.334V425.9a42.667 42.667 0 0 1 85.333 0zM908.63 55.04a42.667 42.667 0 1 1 60.074 60.587l-512 508.416a42.667 42.667 0 0 1-60.075-60.587l512-508.416z"></path>
        </symbol>
        <symbol id="qyb-biaoqing" viewBox="0 0 1024 1024">
            <path d="M512 853.333c188.518 0 341.333-152.815 341.333-341.333S700.518 170.667 512 170.667 170.667 323.482 170.667 512 323.482 853.333 512 853.333zm0 68.267c-226.202 0-409.6-183.398-409.6-409.6S285.798 102.4 512 102.4 921.6 285.798 921.6 512 738.202 921.6 512 921.6zm0-307.2c-94.242 0-170.667-77.21-170.667-170.667h341.334A170.667 170.667 0 0 1 512 614.4zM384 375.467a42.667 42.667 0 1 1 0-85.334 42.667 42.667 0 0 1 0 85.334zm256 0a42.667 42.667 0 1 1 0-85.334 42.667 42.667 0 0 1 0 85.334z"></path>
        </symbol>
        <symbol id="qyb-biaoqing-shield1" viewBox="0 0 1024 1024">
            <path d="M587.025 920.917v.683H512c-226.202 0-409.6-183.398-409.6-409.6S285.798 102.4 512 102.4 921.6 285.798 921.6 512a34.133 34.133 0 0 1-68.267 0c0-188.518-152.815-341.333-341.333-341.333S170.667 323.482 170.667 512 323.482 853.333 512 853.333h75.025v.683a34.133 34.133 0 0 1 0 66.901zm0 .683H512c-226.202 0-409.6-183.398-409.6-409.6S285.798 102.4 512 102.4 921.6 285.798 921.6 512h-68.267c0-188.518-152.815-341.333-341.333-341.333S170.667 323.482 170.667 512 323.482 853.333 512 853.333h75.025V921.6z"></path>
            <path d="M512 614.4a170.667 170.667 0 0 0 170.667-170.667H341.333C341.333 537.19 417.758 614.4 512 614.4zM341.33299999999997 332.8a42.667 42.667 0 1 0 85.334 0 42.667 42.667 0 1 0-85.334 0zM597.333 332.8a42.667 42.667 0 1 0 85.334 0 42.667 42.667 0 1 0-85.334 0z"></path>
        </symbol>
        <symbol id="qyb-hongbao" viewBox="0 0 1024 1024">
            <path d="M477.867 631.467H409.6a34.133 34.133 0 0 1 0-68.267h29.525l-38.673-46.421a34.133 34.133 0 0 1 52.43-43.691L512 544.018l59.119-70.93a34.133 34.133 0 1 1 52.429 43.69L584.875 563.2H614.4a34.133 34.133 0 0 1 0 68.267h-68.267V665.6H614.4a34.133 34.133 0 0 1 0 68.267h-68.267v30.72a34.133 34.133 0 1 1-68.266 0v-30.72H409.6a34.133 34.133 0 0 1 0-68.267h68.267v-34.133zM238.933 224.973c68.301 67.072 156.911 100.522 267.776 100.522 116.02 0 207.6-36.625 277.163-110.045.341-.41.785-.82 1.195-1.23v-9.42a34.133 34.133 0 0 0-34.134-34.133H273.067a34.133 34.133 0 0 0-34.134 34.133v20.173zm0 89.088V819.2a34.133 34.133 0 0 0 34.134 34.133h477.866a34.133 34.133 0 0 0 34.134-34.133V306.176c-75.64 58.368-168.824 87.586-278.358 87.586-104.448 0-194.082-26.59-267.776-79.667zm-68.266-75.025V204.8a102.4 102.4 0 0 1 102.4-102.4h477.866a102.4 102.4 0 0 1 102.4 102.4v614.4a102.4 102.4 0 0 1-102.4 102.4H273.067a102.4 102.4 0 0 1-102.4-102.4V239.002z"></path>
        </symbol>
        <symbol id="qyb-hongbao-shield1" viewBox="0 0 1024 1024">
            <path d="M170.667 239.002V204.8a102.4 102.4 0 0 1 102.4-102.4h477.866a102.4 102.4 0 0 1 102.4 102.4v279.279h-.58a34.133 34.133 0 0 1-67.106 0h-.58V306.21c-75.64 58.368-168.824 87.552-278.358 87.552-104.448 0-194.082-26.59-267.776-79.667V819.2a34.133 34.133 0 0 0 34.134 34.133h307.2a34.133 34.133 0 1 1-.41 68.267h-306.79a102.4 102.4 0 0 1-102.4-102.4V239.002zm614.4-24.781V204.8a34.133 34.133 0 0 0-34.134-34.133H273.067a34.133 34.133 0 0 0-34.134 34.133v20.173c68.301 67.072 156.911 100.522 267.776 100.522 116.02 0 207.6-36.625 277.163-110.045.341-.41.785-.82 1.195-1.23z"></path>
            <path d="M477.867 631.467H409.6a34.133 34.133 0 1 1 0-68.267h29.525l-38.673-46.421a34.133 34.133 0 0 1 52.43-43.691L512 544.018l59.119-70.93a34.133 34.133 0 0 1 52.429 43.69L584.875 563.2H614.4a34.133 34.133 0 1 1 0 68.267h-68.267V665.6H614.4a34.133 34.133 0 1 1 0 68.267h-68.267v30.72a34.133 34.133 0 0 1-68.266 0v-30.72H409.6a34.133 34.133 0 1 1 0-68.267h68.267v-34.133z"></path>
        </symbol>
        <symbol id="qyb-shield" viewBox="0 0 1024 1024">
            <path d="M403.922 786.618a301.493 301.493 0 0 0 370.536-434.15l-370.536 434.15zm-151.45-132.256l367.722-430.834a301.493 301.493 0 0 0-367.621 430.834zm262.701 354.356a502.489 502.489 0 1 1 0-1004.978 502.489 502.489 0 0 1 0 1004.978z" fill="#F05151"></path>
        </symbol>
        <symbol id="qyb-zimu" viewBox="0 0 1024 1024">
            <path d="M170.667 238.933a34.133 34.133 0 0 0-34.134 34.134v477.866a34.133 34.133 0 0 0 34.134 34.134h682.666a34.133 34.133 0 0 0 34.134-34.134V273.067a34.133 34.133 0 0 0-34.134-34.134H170.667zm0-68.266h682.666a102.4 102.4 0 0 1 102.4 102.4v477.866a102.4 102.4 0 0 1-102.4 102.4H170.667a102.4 102.4 0 0 1-102.4-102.4V273.067a102.4 102.4 0 0 1 102.4-102.4zM512 512h273.067a34.133 34.133 0 0 1 0 68.267H512A34.133 34.133 0 0 1 512 512zm-204.8 0h68.267a34.133 34.133 0 0 1 0 68.267H307.2a34.133 34.133 0 0 1 0-68.267zm-68.267 136.533H512a34.133 34.133 0 0 1 0 68.267H238.933a34.133 34.133 0 0 1 0-68.267zm409.6 0H716.8a34.133 34.133 0 0 1 0 68.267h-68.267a34.133 34.133 0 0 1 0-68.267z"></path>
        </symbol>
        <symbol id="qyb-zimu-shield1" viewBox="0 0 1024 1024">
            <path d="M583.714 853.163v.17H170.667a102.4 102.4 0 0 1-102.4-102.4V273.067a102.4 102.4 0 0 1 102.4-102.4h682.666a102.4 102.4 0 0 1 102.4 102.4v210.978h-.546a34.133 34.133 0 0 1-67.174 0h-.546V273.067a34.133 34.133 0 0 0-34.134-34.134H170.667a34.133 34.133 0 0 0-34.134 34.134v477.866a34.133 34.133 0 0 0 34.134 34.134h413.047v.17a34.133 34.133 0 0 1 0 67.926z"></path>
            <path d="M732.98 512.307a222.55 222.55 0 0 0-88.68 67.96H512A34.133 34.133 0 0 1 512 512h216.405c1.536 0 3.072.102 4.574.307zM307.2 512h68.267q34.133 0 34.133 34.133 0 34.134-34.133 34.134H307.2q-34.133 0-34.133-34.134Q273.067 512 307.2 512zM238.93300000000002 648.533H512q34.133 0 34.133 34.134 0 34.133-34.133 34.133H238.933q-34.133 0-34.133-34.133 0-34.134 34.133-34.134z"></path>
        </symbol>
    </svg>
</div>
```

**Comment by realhuyang** [comment]
●  Excuse me, can you tell me how you call this thing: bullets？bullet screen？barrage？Danmaku？preventive barrage？bullet comments？live commenting？
●  I use Google Translate, I do n’t know which word is more appropriate.

**Comment by llacb47** [comment]
What is the word in Chinese, maybe we can figure it out (?)

**Comment by realhuyang** [comment]
Chinese is “弹幕”

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/77270435-4c4ec380-6c82-11ea-9e1d-c02b644775d1.png)
so this is an example of "barrage"? (from bilibili)

**Comment by LGLTeam** [comment]
@realhuyang I would just call it "scrolling text" because the text are scrolling to the left
Niconico also using same feature

**Comment by krystian3w** [comment]
Well, then you need to analyze the EasyList and EasyPrivacy blocks or scriplets.

Unless you find it very annoying, worth blocking in the stock list.

**Comment by Yuki2718** [comment]
Reproduced on Brave and Firefox with default uBO filter lists.
@realhuyang 
Please add
`iqiyi.com#@#+js(aopr, DOMParser)`
to your uBO's "My filters" and see if the issue is resolved, then report it back.

**Comment by Yuki2718** [comment]
For others to confirm: I used this link as the link by OP seemed to be geo-restricted:
`https://www.iqiyi.com/v_19rwvyttw8.html`
Around 12:00 some scrolling comments should appear. I accessed from Hong-Kong because otherwise loading never ended and my current VPN doesn't offer other Chinese location.

**Comment by realhuyang** [comment]
@Yuki2718 
Is it added like this?
![Snipaste_2020-03-25_10-50-25](https://user-images.githubusercontent.com/25172023/77497065-5c83c000-6e87-11ea-8c80-f591571b4f9c.png)

After adding this way, I can’t access it, and it keeps loading.
![iqiyi](https://user-images.githubusercontent.com/25172023/77497118-84732380-6e87-11ea-9c2b-703f2069957f.gif)

**Comment by Yuki2718** [comment]
> 

> Is it added like this?

Correct.

> 
> After adding this way, I can’t access it, and it keeps loading.

Hmmm, I can view the video with the rule as long as accessed from Hong-Kong (the below SS), but it keeps loading if accessed from Japan.
![iqiyi](https://user-images.githubusercontent.com/58900598/77499623-fa7e8700-6e95-11ea-86f0-ba2f9ff5fd23.png)

**Comment by realhuyang** [comment]
I am in mainland China, after adding this rule, whether it is using direct connection or using ss proxy of Hong Kong, Japan, and the United States, it always shows loading.

**Comment by llacb47** [comment]
Maybe conflicting with tampermonkey?

**Comment by realhuyang** [comment]
I closed all plugins except ubo and still shows loading.

**Comment by Yuki2718** [comment]
Now I can view without VPN. Given the rule doesn't block anything, I'm not sure if it's really a matter of the rule.  Can you test allowing all first-party requests as shown in the SS below? You may need to click "domains connected" on first.
![iqiyi](https://user-images.githubusercontent.com/58900598/77513393-417d7400-6eb8-11ea-8d03-e2ce5fb38027.png)

**Comment by krystian3w** [comment]
And need enable "avanced user" mode.

**Comment by realhuyang** [comment]
![Snipaste_2020-03-25_17-10-03](https://user-images.githubusercontent.com/25172023/77520020-8060f900-6ebb-11ea-82a5-f38425cafb86.png)
![Snipaste_2020-03-25_17-09-37](https://user-images.githubusercontent.com/25172023/77520056-8fe04200-6ebb-11ea-984e-b94083836d93.png)
![Snipaste_2020-03-25_17-09-18](https://user-images.githubusercontent.com/25172023/77520110-a7b7c600-6ebb-11ea-9857-9e718257e068.png)

**Comment by realhuyang** [comment]
Maybe we can look at it with remote assistance?

**Comment by lain566** [comment]
> Given the rule doesn't block anything, I'm not sure if it's really a matter of the rule.

@Yuki2718 That filter blocks video ads on my end, it may not block anything for you, because you are using Brave,, that's like using two ad blockers. Have you tried using Chrome/Chromium or Firefox with default settings?

and If I add `iqiyi.com#@#+js(aopr, DOMParser)` I get stuck, same as https://github.com/uBlockOrigin/uAssets/issues/7136#issuecomment-603612373

**Comment by lain566** [comment]
> Can you test allowing all first-party requests as shown in the SS below? You may need to click "domains connected" on first.

I get ads if I do that

![Anotación 2020-03-25 103718](https://user-images.githubusercontent.com/27441315/77522662-dfefe200-6e84-11ea-904e-a4b533f83712.png)

**Comment by lain566** [comment]
@realhuyang Try these filters, that should fix it.
```
iqiyi.com##+js(set, Object.prototype.parseXML, noopFunc)
iqiyi.com#@#+js(aopr, DOMParser)
```

**Comment by realhuyang** [comment]
@lain566 
Okay, that's it!

**Comment by lain566** [comment]
@cjx82630 You may want to add `iqiyi.com##+js(set, Object.prototype.parseXML, noopFunc)`

and remove this filter  `iqiyi.com##+js(aopr, DOMParser)` [cjx82630/cjxlist@de29111](https://github.com/cjx82630/cjxlist/commit/de29111783448ca3436edf16eb5c338f8a3504a6#diff-a07befeff7230db0060d1fbd84efc373R34)

**Comment by Yuki2718** [comment]
@lain566 Well, I always keep all Brave's blocker turned off, if it was turned on you'd seen blockage counter on the lion icon. Actually everything has first tested on Firefox (default profile) and I uploaded SS of Brave only because OP uses Chrome. "The rule" referred to
`iqiyi.com#@#+js(aopr, DOMParser)`
which is obviously not a block but an exception rule, so I still don't understand why it causes never-ending load only for OP and you but not for me. I can still watch the video with the rule as long as I access from Hong Kong, last update for subscription filters is 10h ago so the same as morning. Anyway, thank you for providing a working solution.

![iqiyi](https://user-images.githubusercontent.com/58900598/77535195-8cf64900-6edd-11ea-99f0-3f88ea15a992.png)

**Comment by Yuki2718** [comment]
Okay, now if I accessed from Japan with the rule - loading never ends, but without it I can watch. Requests on each cases are obviously different (say, `data.video.iqiyi.com/videos/other/` was only seen in the Japan case) so it's geo-dependent.

![iqiyi](https://user-images.githubusercontent.com/58900598/77536545-d8a9f200-6edf-11ea-9908-ca4a53985269.png)
