### ISSUE TITLE
duit.cc [anti-adb]

### ISSUE THREAD

**Issue by exodius48** [uBlockOrigin/uAssets#7996]
### URL(s) where the issue occurs

`https://duit.cc/Xx7A51`

### Describe the issue

anti-adblock

### Versions

- Browser/version: [FF 81.0.1 x64]
- uBlock Origin version: [1.30.0]

### Settings

Default , uBO annoyances, easylist cookie, adguard base

**Comment by exodius48** [comment]
@uBlock-user thanks works, but when UBO is active, after click 'get link', it does not redirect to exact link. need to turn off UBO to make it works

**Comment by uBlock-user** [comment]
Can't reproduce that, I get to the destination which is `https://www74.zippyshare.com/v/5m4sZl46/file.html`

**Comment by exodius48** [comment]
> 
> 
> Can't reproduce that, I get to the destination which is `https://www74.zippyshare.com/v/5m4sZl46/file.html`

i get this link after click download `https://duit.cc/getlink.php` tried to refresh page to reveal exact link. probably server sided. thank btw

**Comment by mapx-** [comment]
still getting anti adb, popups, and the behaviour of getlink empty

so, these working on my side

```
@@||duit.cc^$ghide
*$image,redirect-rule=2x2.png,domain=duit.cc
duit.cc##+js(nowoif)
duit.cc##+js(aopr, decodeURI)
duit.cc#@#+js(nano-setInterval-booster)
```

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/01a46d3f8805b38489f3b303cb2258f915188d6c

**Comment by uBlock-user** [comment]
Removed booster, so that should fix the empty getlink issue.

**Comment by mapx-** [comment]
and fixed the popup (when clicking "go")

**Comment by uBlock-user** [comment]
Do you always get a popup or only strangely once ?

**Comment by mapx-** [comment]
always

**Comment by exodius48** [comment]
@mapx- @uBlock-user  weird, i still get anti-adb in this evening. :/

**Comment by uBlock-user** [comment]
@exodius48 force update uBlock Filters list

**Comment by exodius48** [comment]
@uBlock-user  already did. i also disabled all extensions except UBO and reset UBO to default setting too. but still get anti-adb message.
