### ISSUE TITLE
videohelp.com is not loaded completely when I use 1.31.0 or (now) newest v1.31.3rc2

### ISSUE THREAD

**Issue by Klaus1189** [uBlockOrigin/uAssets#8381]
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [x] uBlock Origin is the only extension
    - [x] uBlock Origin with default lists/settings
    - [x] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description

Website is not loaded completely

### A specific URL where the issue occurs

videohelp.com

### Steps to Reproduce

go to videohelp.com

### Expected behavior:

videohelp.com should load completely but without ads

### Actual behavior:

site is not loaded completely, for example new tools and forum is not loaded. I suspect they have a scanner for uBlock usage

### Your environment

* uBlock Origin version: 1.3.1 or v1.31.3rc2
* Browser Name and version: Firefox 84.0
* Operating System and version: Win 10 20H2 latest updates as of today

**Comment by gwarser** [comment]
@Klaus1189 it was fixed three days ago. Go to [uBO Dashboard](https://github.com/gorhill/uBlock/wiki/Dashboard) -> [Filter lists](https://github.com/gorhill/uBlock/wiki/Dashboard:-Filter-lists#update-now) -> click on the clock icon at the end of "uBlock filters" line -> click on "Update now" on top. Alternatively click on "Purge all caches" -> "Update now"

**Comment by krystian3w** [comment]
Try force update filter via free VPN?

**Comment by Klaus1189** [comment]
Now I know why it is not working for me: U use Site layout: Classic
If I use Default, then it is working, but not when I use Classic.
But as a long term user, I prefer Classic.

Try it out. Set it to Classic and the site will not load.

**Comment by uBlock-user** [comment]
> . Set it to Classic at the very bottom of the page and the site will not load.

Set it to `classic` and then click on Change button, layout changes as expected. But after the change, the selection still shows Default as activated and happens without uBlock activate too, so a site issue.

**Comment by krystian3w** [comment]
But procedural filters is too agresive on classic and blue layout: 

`https://www.videohelp.com/software/Plex`:

https://github.com/uBlockOrigin/uAssets/blob/9a141673dddd9256cd65ba073078acf08173e3bb/filters/filters-2020.txt#L5587

![Bez tytułu](https://user-images.githubusercontent.com/35370833/102583595-4698e800-4105-11eb-99cb-d3695a46a8d8.jpg) | ![Przechwytywanie](https://user-images.githubusercontent.com/35370833/102583591-46005180-4105-11eb-822e-1cbdd01ff7a1.JPG)
--- | ---


@Yuki2718

**Comment by lain566** [comment]
Fixed, I can see the breakage.

**Comment by Klaus1189** [comment]
I updated filters list and deleted the cookie(s) of videohelp in my browser and then configured new and it works now. 

Indeed it is weird behavior when you choose your desired style, but always "Default" be "selected". 
I think this is not really a selection of "Default", it is simply picked "Default", it will only take effect when you press on change.
But if I did set it up my way select another style, sometimes I must delete my cookies and start new so I can get Classic 100% and no Thumbnails. 

Anyway thank you for fixing that issue ;-)

**Comment by Klaus1189** [comment]
"unable to reproduce" is wrong in summary, isn't it? There was indeed an issue with specific styles of videohelp.com

**Comment by uBlock-user** [comment]
> There was indeed an issue with specific styles of videohelp.com

Where ? You didn't click on the Change button that's why it wasn't working for you.

**Comment by Klaus1189** [comment]
>  You didn't click on the Change button that's why it wasn't working for you.

I don't get that. I set it to "Classic" and was working for months. So I must have clicked on Change, otherwise I would NOT have seen Classic style - it its the reddish one ;-)
And I have set it to Classic - 100% - No thumbnails months ago. I like that style.
I know that I need to click on the "Change" button to take effect. Strange claim, don't you think?

The reason I opened this issue, is that videohelp loaded only parts, but disabling uBlock fixed it. And today I remebered that I use custom site layout other may not use, so I checked with default style settings and the site loaded completely and can confirm that other may have not used the Classic style. 
Then I changed it again to Classic and it didn't work, again. I know, that there is sometimes an issue where I have to delete the cookies in my browser to get my Classic 100% no thumbnails showing again - this has nothing to do with uBlock, this is an site issue, but I don't know anything about website design, so I don't blame anything or anybody about it. But I know how to "fix" that issue by deleting the cookies and set it up how I want and leave it then.

I did the same thing yesterday with history deletion, cookies deletion, but nothing worked. Today I saw that a commit was added and checked again and now it works. Still thinking about the last claim, but I simply don't get it.

**Comment by uBlock-user** [comment]
> Today I saw that a commit was added and checked again and now it works.

https://github.com/uBlockOrigin/uAssets/commit/156119d71345a0e34e83b15fb8868984224f6787

The blocks a banner, doesn't fix the layout issue you're having. Click the commit and see for yourself.

**Comment by Klaus1189** [comment]
> Always test with default settings + all other extensions disabled if you believe the issue was caused by uBO.
I did that. What's wrong with you?

Still stating I didn't clicked on "Change"

I can only repeat myself that yesterday it did not work with the layout. Today it worked and still does.

What intention do you have in stating such questionable things?

> > Today I saw that a commit was added and checked again and now it works.
> 
> [156119d](https://github.com/uBlockOrigin/uAssets/commit/156119d71345a0e34e83b15fb8868984224f6787)

And exactly that is the part which potentially caused it. The site was loading till the banner would show up, but uBlock blocks it but the rest of the website was not loading.

Please

**Comment by uBlock-user** [comment]
> What intention do you have in stating such questionable things?

Because the layout doesn't change until I click the Change button and since you didn't mention any of this in the very first post of yours it remained a question.

**Comment by Klaus1189** [comment]
> The commit [...] doesn't fix the layout issue you're having. 

> Then I changed it again to Classic and it didn't work, again. I know, that there is sometimes an issue where I have to delete the cookies in my browser to get my Classic 100% no thumbnails showing again - **this has nothing to do with uBlock**, this is an site issue, but I don't know anything about website design, so I don't blame anything or anybody about it. But I know how to "fix" that issue by deleting the cookies and set it up how I want and leave it then.

The site issue is not a uBlock issue. But I said it ealier

**Comment by uBlock-user** [comment]
videohelp.com##div[style]:has(noscript):has(a[href$="?af=m767uti6sqh1dK4C"])

That's the filter that was removed. If you want to try to reproduce the issue, add the above filter to my Filters and see if you can reproduce the issue again.

**Comment by Klaus1189** [comment]
> 
> 
> > What intention do you have in stating such questionable things?
> 
> Because the layout doesn't change until I click the Change button and since you didn't mention any of this in the very first post of yours it remained a question.

I thought you had understood how this site works, I admit it is a bit strange, but I did not program/create or whatever you call it this site. But I think now you know how it works and can follow me and this issue. But please do not be too fast in judging things, like in this case. 

If you still don't trust me, please get me a link to old filters list and I create screenshots - just for you, that with the reddish "Classic" style, beware the style is reddish not black. If it is black it is still the Default one applied. 
I know how that site works, trust me. 

Do me a favour and reread this hole thread and think about it how you reacted. Way too fast. It is not my problem if you judge way too fast in things you don't understand and claim that others, in this case me, don't understand how something works:



> Because the layout doesn't change until I click the Change button and since you didn't mention any of this in the very first post of yours it remained a question.
This is not my fault, it is yours, if you don't understand how this works, but blaiming me is not very nice of you:

> You didn't click on the Change button that's why it wasn't working for you.

**Comment by Klaus1189** [comment]
> 
> 
> `videohelp.com##div[style]:has(noscript):has(a[href$="?af=m767uti6sqh1dK4C"])`
> 
> That's the filter that was removed. If you want to try to reproduce the issue, add the above filter to my Filters and see if you can reproduce the issue again.

I added it and now the issue is here:
https://drive.google.com/file/d/11ilVuJ4lvgWNGsR6gVbD6-2H8eObW4q5/view?usp=sharing

**Comment by krystian3w** [comment]
Private video.

Perhaps it is better to consider the blue and classic code as abandaware.

---
If you find another breakage that disappears with an inactive UBO, please provide a direct link to the bugged part of the site.

**Comment by Klaus1189** [comment]
Please do not judge too fast, exactly this filters was causing it, not me not pressing the Change button. Come on.

> 
> 
> > Today I saw that a commit was added and checked again and now it works.
> 
> [156119d](https://github.com/uBlockOrigin/uAssets/commit/156119d71345a0e34e83b15fb8868984224f6787)
> 
> The commit blocks a banner, doesn't fix the layout issue you're having. Click the commit and see for yourself.
> 
> Always test with default settings + all other extensions disabled if you believe the issue was caused by uBO.

@Yuki2718 why thumbs up, if the statement is wrong. Also very strange person.

**Comment by krystian3w** [comment]
Because we are probably dragging the thread.

Once you've established how the footer widget works, you have to remember to click the "change" button and ignore which dot lights up when you see changes in the page template or use these:

`videohelp.com##+js(ra, checked, form[name="formlayout"] input)`

```css
videohelp.com##form[name="formlayout"] input[value]:not(:checked) ~ #layoutchange
videohelp.com##html:root form[name="formlayout"] input[value]:checked ~ #layoutchange:style(display: inline-block !important)
```

IMO - Only correct detect layout by found cookie:

`layoutcookie:2` or `3` or no exist that cookie.
